leather-io/mono

.github/workflows/build.yml
apps/mobile-wallet/scripts/buildAndroid.js
apps/mobile-wallet/scripts/buildIos.js

Run iOS and Android builds on Github Actions.
Expo tooling is built pretty well to support EAS cloud builds, but not so well for running builds on other types of CI. Thus, i am reusing parts of `expo run:android` and `expo run:ios` scripts that are only responsible for building a release application, without running the dev server or opening the simulator/emulator.
iOS .app and Android .apk files are going to be uploaded to Github Actions as artefacts. Both are drag-and-droppable to their respective simulator / emulator:
https://github.com/leather-wallet/mono/assets/22010816/148e4f24-5992-4480-8b77-467d8d9fc198

ci: Add ios and android builds

---

package-lock.json
packages/tokens/package.json
packages/tokens/src/keyframes.ts
packages/tokens/src/tokens.ts

This PR changes our radii token sizes based on UI design system updates. And, I relocated a new keyframe here for the new dropdown menu and select components.
https://github.com/leather-wallet/extension/issues/4637

refactor: radii sizes and add keyframe

---

packages/tokens/package.json
packages/tokens/src/colors.ts
packages/tokens/src/semantic-tokens.ts

This PR:
- deprecates `brown` colours, renaming as `ink` 
- adds a new transparent colour `transparentInk`
Relates to https://github.com/leather-wallet/extension/issues/4805

chore: migrate colours to ink and remove superflous colours, closes #41

---

packages/tokens/package.json
packages/tokens/src/semantic-tokens.ts

This PR:
- adds the `focus` colour I found a `TODO` for from extension PR #4820
- increments the package number to release https://github.com/leather-wallet/mono/pull/49

chore: add focus to monorepo and increment package

---

packages/tokens/package.json
packages/tokens/src/semantic-tokens.ts

This PR coordinates semantic tokens for red, blue, yellow, and green. Step one is to release this here > then I will install in the extension and replace the ones I removed here.
Please let me know if there are other changes to make here before I merge/release.
https://github.com/leather-wallet/extension/issues/4831

refactor: semantic tokens

---

packages/tokens/src/colors.ts

Use non-transparent colour for action-primary-hover in dark mode to fix broken hover states

fix: primary action hover in dark mode

---

packages/tokens/package.json

Yesterday, I incremented the `token` package version to `11` based on the previous version.
I then did a release `@leather-wallet/tokens@0.0.11` and published the new version. 
After doing that and going to NPM I see we already release version `0.0.13` 2 weeks ago and my latest release was still labelled as `0.0.13`. 
Creating this manual request now but we need a better way so that the `package.json` version is auto updated in each package OR PR's are blocked without an updated package version

chore: update token package version

---

packages/tokens/src/typography.ts

Code text font-size was too large, this is a sync up with the change in the design system

fix: smaller code font-size style

---

packages/types/src/index.ts
packages/types/src/methods/get-addresses.ts

Closes leather-wallet/extension#5314
Promise would return error or success value, yet we only resolve the promise when it's successful.

fix: types success bug

---

.github/actions/provision/action.yml
.github/workflows/release-please.yml

Previous release build failed because pnpm version hadn't been updated in release job. Here, we reuse the provision action with the later version of pnpm.

feat: fix release process

---

packages/ui/package.json

In this PR I include `dist-all/` in the `files: [` array of `package.json` as otherwise it wasn't being published

fix: specify dist folder to include in publish

---

packages/ui/src/components/dialog/dialog-header.web.tsx
packages/ui/src/components/dialog/index.ts
packages/ui/web.ts

This PR moves the `DialogHeader` to the monorepo. Following on from work in https://github.com/leather-io/extension/pull/5588/

Move DialogHeader to monorepo

---

packages/ui/README.md

I mistakenly updated this in the README thinking it was the `tsup` config

chore: fix mistake in README

---

packages/bitcoin/package.json
packages/bitcoin/tsup.config.ts
packages/constants/package.json
packages/constants/tsup.config.ts
packages/crypto/package.json
packages/crypto/tsup.config.ts
packages/models/package.json
packages/models/tsup.config.ts
packages/rpc/package.json
packages/rpc/tsup.config.ts
packages/stacks/package.json
packages/stacks/tsup.config.ts
packages/tokens/tsup.config.ts
packages/ui/tsup.config.web.ts
packages/utils/package.json
packages/utils/tsup.config.ts

I've been running into many issues relating to `pnpm build:watch`. There's an open issue where `tsup --watch` doesn't output the `d.ts` file. https://github.com/egoist/tsup/issues/970.
Further, the build order isn't respected when running `build:watch` meaning the build gets errors because one package is built before the other. This PR ensures watch outputs the d.ts with the fix mentioned in the issue, and remedies many of the build order issues by _not_ cleaning the repo on every build (which would normally clear the d.ts). `clean: false` is safe to set because our release job will always be starting from a clean state anyway

fix: improve watch mode

---

packages/query/index.ts
packages/query/src/bitcoin/clients/best-in-slot.ts
packages/query/src/bitcoin/stamps/stamps-by-address.query.ts
packages/query/src/leather-query-provider.tsx
packages/query/src/utils.ts

We can catch Zod errors better elsewhere via configuration of `QueryClient`. This PR removes the specific Zod error handling, fixes a known Stamp response error, and exports a analytics querying helper.

fix(query): remove internal zod fail handling

---

apps/mobile/src/state/keychains/bitcoin/bitcoin-keychains.slice.ts
apps/mobile/src/state/keychains/keychains.ts
apps/mobile/src/state/keychains/stacks/stacks-keychains.slice.ts

Closes leather-io/issues#246
Ensures Stacks accounts are filtered by address index, not account index

fix(mobile): stacks account grouping, closes leather.io/issues#246

---

.github/workflows/release-please.yml

Untested, but as far as I understand, when we merge the release PR, this'll trigger the extension to run the upgrade job

ci: fire action to trigger extension pr

---

.github/workflows/release-please.yml

Only run job when a release is created

ci: fix issue with release job action firing on prs

---

packages/ui/src/components/dialog/dialog-footer.web.tsx
packages/ui/src/components/dialog/dialog-header.web.tsx
packages/ui/src/components/dialog/dialog.web.stories.tsx
packages/ui/src/components/dialog/dialog.web.tsx

This PR:
- refactors `Dialog` to locate the `Footer` component local to it and avoid using it in the extension
- Adds a min height to dialog headers

fix: dialog header height + refactor dialog footer

---

packages/query/src/stacks/token-metadata/fungible-tokens/fungible-token-metadata.hooks.ts
packages/query/src/stacks/token-metadata/fungible-tokens/fungible-token-metadata.query.ts

This pr prevents ft tokens unnecessary requerying. same logic as for nfts [here](https://github.com/leather-io/mono/pull/377)

feat: prevent ft tokens unnecessary requerying

---

packages/ui/src/components/box/hstack.native.tsx
packages/ui/src/components/box/stack.native.tsx
packages/ui/src/components/item-layout/item-layout.native.stories.tsx
packages/ui/src/components/item-layout/item-layout.native.tsx

This adds a native version of `ItemLayout`. Using the web styles and its not looking quite right:
https://github.com/user-attachments/assets/ad0b40dd-8657-4548-bfbf-74841ae043fd
On native, it seems like `alignItems` doesn't support `start` / `end` so I have instead used `flex-start` and `flex-end`, maybe thats the issue? 
When I check the **web.storybook** `ItemLayout` is not loading at all there so I can investigate fixing that and compare

chore: item layout mobile

---

packages/ui/src/components/dialog/index.ts
packages/ui/src/components/sheet/index.ts
packages/ui/src/components/sheet/sheet-footer.web.tsx
packages/ui/src/components/sheet/sheet-header.web.tsx
packages/ui/src/components/sheet/sheet.web.stories.tsx
packages/ui/src/components/sheet/sheet.web.tsx
packages/ui/web.ts

This PR changes the name of the web `Dialog` component to be `Sheet` as per https://github.com/leather-io/issues/issues/268

fix: rename dialog as sheet

---

packages/ui/src/components/sheet/sheet-header.web.tsx

This PR makes an adjustment to the padding of the `BigTitle` (large) variant of the `SheetHeader` to fix issues mentioned in https://trustmachines.slack.com/archives/C05LRS7G44R/p1724942231015239?thread_ts=1724305603.462199&cid=C05LRS7G44R

fix: adjust BigTitle padding and close, ref leather-io/extension#5802

---

packages/ui/src/components/cell/cell.native.stories.tsx
packages/ui/src/components/flag/flag.web.stories.tsx
packages/ui/src/components/item-layout/item-layout.native.stories.tsx
packages/ui/src/components/item-layout/item-layout.native.tsx
packages/ui/src/components/item-layout/item-layout.web.stories.tsx

This is a small PR to:
- stop using icons in storybook and use placeholder images instead (until SVG issue resolved)
- refactor `ItemLayout` to use the correct chevron icon (CSS transform wasn't right on native)
- add the `Switch` variant to the `Cell` storybook
https://github.com/user-attachments/assets/f84c5ac7-b603-4469-ad7b-30146b7a3a02

feat: cell component improvements

---

packages/ui/package.json
packages/ui/src/.storybook-web/main.ts
packages/ui/src/icons/docs/icons.mdx
pnpm-lock.yaml

This fixes running the new icons with storybook for web in the UI library. It doesn't appear the script for running storybook with `native` is setup, or what am I missing?

fix: storybook icons

---

apps/mobile/src/app/wallet/wallet-settings/configure/[wallet]/[account].tsx
apps/mobile/src/components/browser/browser-empty-state.tsx
apps/mobile/src/components/home/account-card.tsx
apps/mobile/src/components/home/my-accounts.tsx
apps/mobile/src/hooks/get-addresses.ts
apps/mobile/src/locales/en/messages.po
apps/mobile/src/locales/pseudo-locale/messages.po
apps/mobile/src/state/accounts/accounts.slice.ts
apps/mobile/src/state/keychains/stacks/stacks-keychains.slice.ts
apps/mobile/src/state/settings/settings.slice.ts
apps/mobile/src/state/wallets/wallets.slice.ts
packages/bitcoin/CHANGELOG.md
packages/bitcoin/package.json
packages/crypto/src/derivation-path-utils.ts
packages/crypto/src/index.ts
packages/crypto/src/keychain.ts
packages/crypto/src/signer/signer.ts
packages/stacks/src/index.ts
packages/stacks/src/signer/signer.spec.ts
packages/stacks/src/signer/signer.ts
packages/stacks/src/stacks.utils.spec.ts
packages/stacks/src/stacks.utils.ts
pnpm-lock.yaml

This PR adds code for the Stacks signer. This gets initialised in part of the keychain selector.
Next, I aim to figure out the best way to consume these signers in the app. I am **very reluctant** to continue using the pattern from the extension where we do something like
```ts
const signer = useCurrentAccountStacksSigner(); // `signer | undefined`
```
Instead I want a pattern where we pass signers around dynamically, which might look something like:
```tsx
function Assets () {
return signers.map(signer => {
switch (signer.type) {
case 'stacks': return <StacksSigner signer={signer} />
case 'bitcoin': return <BitcoinSigner signer={signer} />
}
});
}
```
This way, we can consume the signer well in the knowledge it exists
or 
```tsx
<SignerLoader requiredKeys={[keyOrigin1, keyOrigin2]} …
```

feat: shared stacks signing logic

---

apps/mobile/src/components/create-new-wallet/mnemonic-display.tsx
apps/mobile/src/locales/en/messages.po
apps/mobile/src/locales/pseudo-locale/messages.po

This is a small PR to change the secondary action buttons on the mnemonic form

fix: update mnemomic secondary action buttons, ref leather-io/issues#318

---

packages/ui/src/components/avatar/avatar.native.tsx
packages/ui/src/components/box/hstack.native.tsx
packages/ui/src/components/box/stack.native.tsx
packages/ui/src/components/chip/chip.native.tsx

This PR addresses an issue with how I was using `defaultProps` in some of our UI components

fix: deprecate usage of `defaultProps` and extend BoxProps

---

packages/query/package.json
pnpm-lock.yaml

This PR updates `alex-sdk` in the queries package so we can then update it in the `extension`. 
We have an [extension PR](https://github.com/leather-io/extension/pull/5852) but it's failing on a type error due to different package versions. 
```
src/app/pages/swap/alex-swap-container.tsx:65:22 - error TS2345: Argument of type 'import("/Users/petew/src/leather/extension/node_modules/.pnpm/alex-sdk@2.1.3_@stacks+network@6.13.0_encoding@0.1.13__@stacks+transactions@6.15.0_encoding@0.1.13_/node_modules/alex-sdk/dist/currency").Currency' is not assignable to parameter of type 'import("/Users/petew/src/leather/extension/node_modules/.pnpm/alex-sdk@2.1.4_@stacks+network@6.13.0_encoding@0.1.13__@stacks+transactions@6.15.0_encoding@0.1.13_/node_modules/alex-sdk/dist/currency").Currency'.
65 …
```

fix: update alex-sdk

---

packages/ui/src/components/collectibles/web/image-unavailable.web.tsx

This PR fixes a mistake I made when migrating some components in https://github.com/leather-io/extension/pull/5876/

fix: correct broken import path for web icon

---

packages/ui/src/components/approver/animations/approver-animation.web.tsx
packages/ui/src/components/approver/components/approver-container.web.tsx
packages/ui/src/components/approver/components/approver-section.web.tsx

Some small changes to `<Approver />` that tighten up some of the animations, and makes the inner container full width.

fix(ui): approver updates, animations

---

packages/ui/package.json
packages/ui/src/.storybook-web/preview.ts
packages/ui/src/components/approver/approver-context.shared.ts
packages/ui/src/components/approver/approver.web.tsx
packages/ui/src/components/approver/components/approver-actions.web.tsx
packages/ui/src/components/approver/components/approver-container.web.tsx
packages/ui/src/components/approver/components/approver-header.web.tsx
packages/ui/src/components/approver/stories/approver-demo.web.tsx
packages/ui/src/components/approver/stories/approver.web.stories.tsx
packages/ui/src/components/flag/flag.web.stories.tsx
packages/ui/src/components/flag/flag.web.tsx
packages/ui/src/components/tooltip/basic-tooltip.web.tsx
packages/ui/src/components/tooltip/tooltip.web.tsx
pnpm-lock.yaml

- Animates the tooltip on exit, otherwise it feels kinda janky when it animates in then abruptly disappears 
- Renames `info` element in Approver to avoid being tooltip specific
- I've also added back Flag controls, so we can highlight how it can be used for different layouts
- Fixes Flag not responding to all controls 
https://github.com/user-attachments/assets/6c688d01-292a-40e9-8efe-88811ccd7749

fix(ui): add tooltip exit animation

---

.github/actions/eas-deploy-android/action.yml
.github/actions/eas-deploy-ios/action.yml
.github/workflows/eas-deploy.yml
.github/workflows/release-please.yml
apps/mobile/android/app/build.gradle
apps/mobile/eas.json

This PR adds Github actions for build the Leather mobile app for Android. Outside of this build a number of steps have been taken to support these builds:
1. A Play Console application has been created, as well as a Google Services account. The manual step of uploading an initial build has also already been done. 
2. EAS has been updated with proper credentials to sign Android builds.
3. Proper Keychains have been created and shared with the team.
4. Correct ENV secrets have been added.
This MR accomplishes the following:

Add EAS CI support for Android

---

packages/bitcoin/src/bitcoin.utils.ts
packages/models/src/network/network.model.ts
packages/query/src/bitcoin/bitcoin-rate-limiter.ts

Ref LEA-1406
This PR adds the config for testnet4. Testnet3 is pretty unusable at this point, a more reliable testnet'll help me build the balance service.
Note that this PR introduces a `BitcoinNetwork` concept, reflecting the ones available: mainnet, testnet3 and testnet4 etc, which are both instances of `BitcoinMode` of `testnet`.

feat: add testnet4 config

---

apps/mobile/src/components/network-badge.tsx

Easy PR hooking up the network badge in the header to the preferred network setting. I did an OTA update from Crowdin to get the english translation working.

fix: network badge, closes LEA-1531

---

docs/extension-development.md
packages/analytics/.env.example
packages/analytics/.eslintrc.yml
packages/analytics/.gitignore
packages/analytics/README.md
packages/analytics/package.json
packages/analytics/src/client.spec.ts
packages/analytics/src/client.ts
packages/analytics/src/index.ts
packages/analytics/src/types.ts
packages/analytics/tsconfig.json
packages/analytics/tsup.config.ts
packages/analytics/vitest.config.js
pnpm-lock.yaml
turbo.json

Update Oct 18, 2024
I totally refactored this and opted to keep the existing event names and naming conventions, as well as parameters. This will allow for a seamless first pass at adding this to `extension`, essentially will be a 1:1 replacement with some nice type enforcement. 
Instead of adding methods to a class per event I also moved to the recommendation of using a type and enforcing what can be passed based on the type. 
Also, tests!
- ~Created two entry points for analytics package: one for web using analytics browser client from segment, and one for native using segment client from react native.~
- Injected into a generic analytics client with configurable options.
- Planning to make generic functions private and add specific methods for tracking events.
- ~Proposing to use …

Create a simple event tracking package

---

packages/bitcoin/src/bitcoin-signer.ts
packages/bitcoin/src/bitcoin.utils.spec.ts
packages/bitcoin/src/bitcoin.utils.ts
packages/bitcoin/src/lookup-derivation-by-address.spec.ts
packages/bitcoin/src/lookup-derivation-by-address.ts
packages/bitcoin/src/p2wpkh-address-gen.ts
packages/constants/src/index.ts

Pulling this out of some WIP work in another branch to merge separately. 
This function takes an address and tries to find the corresponding path. I don't really want to need this function, it's a very expensive look up, but, given the xpub API response doesn't include the derivation path, in order to support sends on non-zero index, we need this check.

feat(bitcoin): recursive address look up helper

---

apps/mobile/package.json
packages/models/package.json
packages/query/package.json
packages/query/src/bitcoin/address/transactions-by-address.query.ts
packages/query/src/stacks/token-metadata/fungible-tokens/fungible-token-metadata.query.ts
packages/query/src/stacks/token-metadata/non-fungible-tokens/non-fungible-token-metadata.query.ts
packages/rpc/package.json
packages/utils/src/time.ts
pnpm-lock.yaml

Some requests can be cached near-indefinitely, such as FT metadata which very infrequently changes. This endpoint is fetched each SIP10 token a user may have, which could be 10s or 100s of requests for well-used wallets.
We had efforts to cache this for 30 days with a staleTime of a week. I noticed in debugging extension that we would always refetch token metadata, resulting in a huge amount of wasteful requests being made to the Hiro API.
Because the `gcTime` was set to a number greater than the maximum of 2,147,483,647 supported by `setTimeout`, the value fails silently. Setting a lower gcTime, or setting it to `Infinity` (to disable it) fixes this issue. This data can be cached indefinitely, so I've set it to `Infinity`.
We've had so many discussions talking about ideas like cycling …

fix(query): gcTime using too big of a number for javascript

---

apps/mobile/package.json
apps/mobile/src/scripts/injected-provider.js
packages/query/package.json
packages/query/src/rate-limiter/queue-class.ts
pnpm-lock.yaml

This PR [originates from](https://github.com/leather-io/mono/pull/542/files) and includes two important steps for the query package to work on React Native:
- [chore: use uuid instead of crypto.randomID to support RN](https://github.com/leather-io/mono/commit/7125dbc303ead3e90a475f3a64c07c6cec54ae8f) 
- [chore: downgrade p-queue and fix version to prevent throwIfAborted error](https://github.com/leather-io/mono/commit/76d5ea9e9d9d9d31e0c891497eb0dbac6b0159e3)
I need to use uuid as crypto.randomID seems to be not working on React Native (I tried polyfills but this is easier)
If I don't do this queries throw the error: `"failureReason": [TypeError: crypto.randomUUID is not a function (it is undefined)]`
I am rolling back p-queue a version and setting it to 7.4.1 as otherwise queries will …

Updates to support query package in React Native

---

packages/query/src/bitcoin/runes/runes-ticker-info.query.ts

This PR changes the API response field used for Rune market price info.
The current field from the [BestInSlot API](https://docs.bestinslot.xyz/reference/api-reference/ordinals-and-brc-20-and-runes-and-bitmap-v3-api-mainnet+testnet+signet/runes#runes-single-ticker-info) (`min_listed_unit_price_in_sats`) returns rune prices (and therefore balances) significantly lower than those [quoted in their UI](https://bestinslot.xyz/runes).
The updated field `avg_unit_price_in_sats` (with `min_listed_unit_price_in_sats` as a fallback) seems to be more in-line with the price shown on BIS.

refactor: change rune market data to use avg price field

---

.github/workflows/publish-architecture.yml
architecture/leather-architecture.d2

Mission critical work, see theme change as you update theme mode on macos

ci: add dark mode to architecture diagram

---

packages/ui/native.ts
packages/ui/src/components/numpad/numpad-key.native.tsx
packages/ui/src/components/numpad/numpad.native.stories.tsx
packages/ui/src/components/numpad/numpad.native.tsx

Adds an initial version of the numeric pad.
* Currently supports two layouts: numeric and decimal, but is built with extensibility in mind, in case we need more variations in the future
* Locale-aware: needs to be supplied with a locale identifier string to display the appropriate decimal separator.
* Fully controlled: I'm on the fence about supporting uncontrolled mode for special use-case components like this, but open to suggestions.
https://github.com/user-attachments/assets/a5440e40-eea7-4d31-940a-3c7a91801b65
Some WIP improvements that will come after this PR, some need discussion, marked as TBD:
* Use Pressable internally, add less generic pressed state (to be designed)
* Use SVGs for visual labels for perfect optical alignment
* Use haptic feedback **(TBD)**
* Add disabled state …

feat: add numpad component, closes LEA-1647

---

packages/query/src/bitcoin/ordinals/inscriptions.hooks.ts

This bug relates to https://github.com/leather-io/extension/pull/5926, where inscriptions were persisting between accounts.
The issue was that I'd set the query key too short, as the first bytes of the xpub are same between accounts. Increasing the amount of xpub used in the query key reaches the unique bytes by account.

fix(query): too short key identifier

---

packages/analytics/src/client.spec.ts
packages/analytics/src/client.ts
packages/analytics/src/events.ts
packages/analytics/src/types.ts

Some small compatibility and type refactors for using this client in the extension codebase.
- Made some events a bit more permissive
- Made the generic interface types more permissive for better compatibility between browser/native segment client
- Pass through function calling for methods we don't need types on right now (screen, page, identify
- Surfaced underlying `client` in the analytics for flexibility
- Updated tests

refactor(analytics)!: prepare analytics client for use in extension

---

packages/query/index.ts
packages/query/src/query-prefixes.ts
packages/query/src/stacks/bns/bns-v2-client.ts
packages/query/src/stacks/bns/bns.query.ts
packages/query/src/stacks/bns/bns.schemas.ts
packages/query/src/stacks/bns/bns.utils.spec.ts
packages/query/src/stacks/bns/bns.utils.ts

This pr adds bns v2 client and zonefile request

feat: add bns v2 client and zonefile request

---

packages/query/index.ts
packages/query/src/query-prefixes.ts
packages/query/src/stacks/bns/bns-v2-client.ts
packages/query/src/stacks/bns/bns.schemas.ts

@alter-eggo tests were failing even though functionality worked because our mocked responses didn't conform to schema. 
This PR exports all schemas as validators. When declaring mocks, let's do so with a `schema.parse(mock)`, so we can verify they match.

fix(query): bns schemas, exports

---

packages/models/src/network/network.model.ts

fix: incorrect port on sbtc dev env mempool.space instance

---

apps/mobile/src/components/widgets/accounts/accounts-widget.tsx
apps/mobile/src/components/widgets/collectibles/collectibles-widget.tsx
apps/mobile/src/components/widgets/components/widget/widget-header.tsx
apps/mobile/src/components/widgets/components/widget/widget.tsx
apps/mobile/src/components/widgets/tokens/tokens-widget.tsx

Part of [LEA-659](https://linear.app/leather-io/issue/LEA-659/define-tapon-press-effect-for-interactive-elements)
Converts the Widget into a Radix-style compound component in preparation for list item animations, but also in an attempt to standardize with other similar components like the [Approver](https://github.com/leather-io/mono/blob/dev/packages/ui/src/components/approver/approver.web.tsx)
```
<Widget
header={
<WidgetHeader />
}
>
...
</Widget>
```
```
<Widget>
<Widget.Header>
<Widget.Title />
</Widget.Header>
<Widget.Body>
...
</Widget.Body>
</Widget>
```
This significantly reduces the prop drilling and subsequently the need to expose more props, de-couples it from ScrollView, some spacing opinions (padding, gaps, etc.), and replaces the dependency on `sheet` with a generic action.

refactor: convert widget into compound components

---

apps/mobile/src/queries/balance/stacks-balance.query.ts
apps/mobile/src/queries/market-data/stx-market-data.query.ts

This PR refactors STX balances to use the new market data service

chore: use market data service for STX balances

---

apps/mobile/ios/Podfile.lock
apps/mobile/ios/leatherwalletmobile.xcodeproj/project.pbxproj
apps/mobile/package.json
apps/mobile/src/app/(home)/settings/display/index.tsx
apps/mobile/src/app/_layout.tsx
apps/mobile/src/store/settings/settings.read.ts
apps/mobile/src/store/settings/settings.ts
apps/mobile/src/store/settings/settings.write.ts
apps/mobile/src/store/settings/utils.ts
packages/ui/native.ts
packages/ui/package.json
packages/ui/src/components/pressable/pressable.native.tsx
packages/ui/src/hooks/use-haptics.native.ts
packages/ui/src/hooks/use-haptics.native.tsx
packages/utils/src/index.ts
pnpm-lock.yaml

Part of [LEA-659](https://linear.app/leather-io/issue/LEA-659/define-tapon-press-effect-for-interactive-elements)
Adds haptics support to Pressable and a hook to invoke haptics in isolation:
```
<Pressable haptics="soft" />
```
```
<Pressable haptics={ onPress: 'soft', onLongPress: 'rigid' } />
```
Simple, safe-wrapper around `expo-haptics`.
```
const triggerHaptics = useHaptics()
triggerHaptics('success');
```
This really only exists for few  reasons:
1. Ability to normalize haptic feedback across platforms in the future: Android vibrations equivalent can be often much stronger. Will test soon enough.
2. Add ability to disable hooks in app settings in the future. This is actually the only reason why this is a hook and not a simple factory.
3. Avoid importing enums from `expo-haptics` …

feat: add haptics support to Pressable

---

apps/mobile/src/queries/market-data/btc-market-data.query.ts
packages/query/src/bitcoin/ordinals/brc20/brc20-tokens.query.ts
packages/query/src/common/alex-sdk/alex-sdk-latest-prices.query.ts
packages/query/src/common/alex-sdk/alex-sdk-swappable-currency.query.ts
packages/query/src/common/market-data/market-data.query.ts

We've had a handful of caching-related sounding issues raised lately. Looking into this because of @camerow's [comment here](https://github.com/leather-io/extension/issues/5981#issuecomment-2491914079).
Because of the default very-aggressive React Query settings, we've gotten into the habit of setting the queries not to update with code like:
```ts
refetchOnMount: false,
refetchOnReconnect: false,
refetchOnWindowFocus: false,
```
Unless we have a `refetchInterval` set—which in many cases we don't—this means that we never refetch the data, even if it is stale.
Typically, I'd say that we should we refetching on mount, at the very least. If the stale values are set correctly, it should also be fine to refetch on the others too. I think we should just go and change the default settings to be …

fix(query): fetch on mounts

---

apps/mobile/src/components/amount-field/amount-field-primary-value.tsx
apps/mobile/src/components/amount-field/amount-field-secondary-value.tsx
apps/mobile/src/components/amount-field/amount-field.tsx
apps/mobile/src/components/amount-field/amount-send-max-button.tsx
packages/ui/src/assets/icons/arrow-top-bottom-16-16.svg
packages/ui/src/assets/icons/arrow-top-bottom-24-24.svg
packages/ui/src/icons/arrow-top-bottom-icon.native.tsx
packages/ui/src/icons/index.native.ts

Part of [LEA-1720](https://linear.app/leather-io/issue/LEA-1720/send-form-amount-field)
Adds the AmountField component for the Send form
https://github.com/user-attachments/assets/eb5ef453-cdb2-457e-97bb-95c9ea82081e
@fbwoolf I was initially intending to plug this into the form myself, but decided against it for two reasons:
1. Still behind the curve of doing calculations correctly based on market data, chosen currency, etc., it will probably take me much longer
2. Not sure what stage the form development is in, as I've noticed some things like error handling are still in progress.
I've made the component domain-agnostic enough to be easily integrated. Formatting & currency conversion when swapping values is done via inversion of control. Here's a basic example I've put together based on …

feat: add amount field component

---

apps/mobile/src/components/widgets/accounts/accounts-widget.tsx
apps/mobile/src/components/widgets/collectibles/collectibles-widget.tsx

The scrollability is obvious enough from the designs. Unlike with browsers, I can't think of any obvious gotchas related to not having scrollbars. Will revisit with a less destructive approach if anything turns up.
https://github.com/user-attachments/assets/90865f09-bb6b-49f3-9e1b-b1e8d6d1c1d3

fix: hide the scrollbar on accounts and collectibles widgets, closes LEA-1432

---

apps/mobile/ios/leatherwalletmobile/Info.plist

This takes @edgarkhanzadian 's [fix for the app store](https://github.com/leather-io/mono/pull/641/files#r1863451352) so that we don't need to manually approve new testflight builds

fix: fix appstore connect deployment to bypass manual approval

---

apps/mobile/src/queries/balance/bitcoin-balance.query.ts
apps/mobile/src/queries/balance/stacks-balance.query.ts
packages/models/src/crypto-assets/crypto-asset-balance.model.ts
packages/query/src/bitcoin/runes/runes.utils.ts
packages/query/src/bitcoin/stamps/stamps-by-address.hooks.ts
packages/query/src/stacks/stx20/stx20-tokens.hooks.ts
packages/query/src/stacks/token-metadata/fungible-tokens/fungible-token-metadata.hooks.ts
packages/services/package.json
packages/services/src/balances/bitcoin-balances.service.ts
packages/services/src/balances/bitcoin-balances.utils.ts
packages/services/src/index.ts
packages/services/src/infrastructure/api/hiro/hiro-leather-headers.ts
packages/services/src/infrastructure/api/hiro/hiro-request-priorities.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.client.ts
packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/cache/http-cache.utils.ts
packages/services/src/inversify.config.ts
packages/services/src/market-data/market-data.service.ts
packages/utils/src/assets/balance-helpers.ts
packages/utils/src/index.ts
pnpm-lock.yaml

Implements a BTC balance service and applies it in `mobile`. 
- BTC balances include the total of both the Segwit + Taproot account.
- Service does not yet filter out pending balances or protected balances (inscriptions, runes, etc..).
- Uneconomical balances are filtered out using a basic/temporary rule of <10k sats.
- Includes rework to `CryptoAssetBalance` model.
- Creates a new `LeatherApiClient`
- Closes [LEA-1793](https://linear.app/leather-io/issue/LEA-1793/fix-balances-for-new-accounts-that-are-showing-values)
- Closes [LEA-1761](https://linear.app/leather-io/issue/LEA-1761/stx-market-data-returns-incorrect-precision)
We will continue to extend service-based balances functionality from here, including the incorporation of STX and other asset balances, and additional UTXO filtering …

feat: balances service, closes LEA-1707 LEA-1793 LEA-1761

---

apps/mobile/src/app/(home)/create-new-wallet.tsx
apps/mobile/src/features/balances/bitcoin/bitcoin-balance.tsx
apps/mobile/src/features/balances/stacks/stacks-balance.tsx
apps/mobile/src/features/balances/token-balance.tsx
apps/mobile/src/features/settings/wallet-and-accounts/wallet-card.tsx

In our current Testflight build, some of our CrowdIn translations are not loaded and instead we are showing the key.
I'm still investigating why they aren't loaded properly build but thought it could be prudent to hardcode the text for now so the correct text will appear now and we can do some pre-release tests.
This is an interim solution to make what we have now more releasable pending fixing the underlying problem

fix: hardcode broken translations for leatherhood release, ref LEA-1780

---

packages/ui/src/components/approver/components/approver-actions.native.tsx
packages/ui/src/components/approver/components/approver-advanced.native.tsx
packages/ui/src/components/approver/components/approver-container.native.tsx
packages/ui/src/components/approver/components/approver-footer.native.tsx
packages/ui/src/components/approver/components/approver-header.native.tsx
packages/ui/src/components/approver/components/approver-section.native.tsx
packages/ui/src/components/badge/badge.native.tsx
packages/ui/src/components/highlighting/highlighter.native.tsx

Switch out `import {} from 'native'` with relative imports to avoid Storybook Native crashing from unresolved tsconfig paths.

fix: replace barrel imports with relative paths

---

packages/query/src/common/alex-sdk/alex-sdk.hooks.ts

Updating the SwapAsset type bc a bit outdated with the bitflow integration. It is a bit confusing to keep `Currency` as a type from the alex-sdk on the asset model. Also, I need to expand the icon type to accept BTC and sBTC icons.

fix: swap asset type

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/app/(home)/settings/display/index.tsx
apps/mobile/src/app/(home)/settings/index.tsx
apps/mobile/src/app/(home)/settings/wallet/configure/[wallet]/index.tsx
apps/mobile/src/components/action-bar/action-bar-container.tsx
apps/mobile/src/components/add-wallet/add-wallet-sheet.layout.tsx
apps/mobile/src/components/headers/components/header-options.tsx
apps/mobile/src/utils/feature-flag.ts

This PR adds a basic feature flag based on the users `NODE_ENV` to hide some things in the mobile app that aren't ready. 
It works off [this notion doc](https://www.notion.so/trustmachines/Leatherhood-First-Release-151d74b694c780cc859ecf4e2a979dd5) which I made [this issue](https://linear.app/leather-io/issue/LEA-1818/leatherhood-cleanup) for. 
On that document it says to hide some things and disable others, however when disabling there is currently no extra visual state to signify it to users so I decided to just hide everything. I can change this as desired but thought it best to first hide. 
You can see a demos here of
https://github.com/user-attachments/assets/611c97a3-8640-4e88-812c-bdb47401aab3
https://github.com/user-attachments/assets/f8049a04-eaa5-446f-939a-a95484576a90
Here is a …

fix: gate features not ready for production release

---

apps/mobile/src/components/widgets/accounts/components/cards/add-account-card.tsx

Adds a missing color to the plus icon.

fix: add correct color to add account card icon, closes LEA-1821

---

apps/mobile/src/components/headers/components/header-options.tsx

This PR adds a network bage to the `Home` screen when the network is not `mainnet`. 
Pending design input on the exact positioning
https://trustmachines.slack.com/archives/C05LRS7G44R/p1733382163809769

fix: add network badge to home screen if not mainnet, ref LEA-1815

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/app/(home)/account/[account]/account-overview-card.tsx
apps/mobile/src/app/(home)/settings/display/index.tsx
apps/mobile/src/app/(home)/settings/wallet/configure/[wallet]/[account]/choose-avatar.tsx
apps/mobile/src/app/(home)/settings/wallet/configure/[wallet]/[account]/index.tsx
apps/mobile/src/components/widgets/accounts/accounts-widget.tsx
apps/mobile/src/features/accounts/account-selector/account-selector-sheet-header.tsx
apps/mobile/src/features/accounts/account-selector/account-selector-sheet.layout.tsx
apps/mobile/src/features/accounts/account-selector/account-selector-sheet.tsx
apps/mobile/src/features/accounts/components/account-card.tsx

This PR has a batch of updates for the leatherhood release:
- [fix: adjust horizontal alignment of account page, ref #1820](https://github.com/leather-io/mono/pull/689/commits/e03e2b32a755d152a8cdbb3c8a06e57331cb9d87) 
- [fix: add wallet name and header to account selector, ref #](https://github.com/leather-io/mono/pull/689/commits/a387577cef031164fff47a94d8b7a52cf5f39e33)[LEA-1828](https://linear.app/leather-io/issue/LEA-1828)
- [fix: add wallet name to configure account card, ref #](https://github.com/leather-io/mono/pull/689/commits/6c52af7d853b628e6cf92101ab204d7081c42a64)[LEA-1828](https://linear.app/leather-io/issue/LEA-1828)
- turn off `ActionBar` (again)
- [[fix: remove your collecibles, ref #1822](https://github.com/leather-io/mono/pull/689/commits/82beccee137ccece7c157fec92deb875 …

fix: miscellaneous leatherhood fixes 

---

apps/mobile/src/components/page/page.layout.tsx

This PR adds a pull to refresh to `Home` + the `Account` page. 
On refresh I invalidate all queries: 
https://github.com/user-attachments/assets/a338f1f9-caa3-422b-89ea-d78719890604

fix: add pull to refresh to home and accounts, ref LEA-1814

---

apps/mobile/src/components/action-bar/action-bar-container.tsx
apps/mobile/src/components/headers/components/header-options.tsx
apps/mobile/src/components/headers/home-header.tsx
apps/mobile/src/features/settings/network-badge.tsx

I thought I had merged this work last week but I actually lost it in a rebase so re-did it:
- hide action bar in production version
- only show network badge if non mainnet and adjust position on home screen

leatherhood: pre release cleanup

---

packages/utils/src/money/calculate-money.ts

This PR updates the `sumMoney` utility to avoid an unnecessary type conversion from `BigDecimal` to `number`, which was leading to a loss of precision and inaccurate calculation.
This fixes a bug in mobile where some zero balances are displaying as "-$0.00" or  "<$0.01". 
The bug originated in the sub-balance calculations of the new balance helper function `createBtcCryptoAssetBalance` in `@leather.io/utils`, which utilizes the `sumMoney` function. The rounded balance returned by `sumMoney` is subsequently subtracted from the original total, causing very small positive or negative differences (depending on the direction of the rounding).

fix: remove number conversion in sumMoney utility

---

apps/mobile/src/app/(home)/create-new-wallet.tsx
apps/mobile/src/components/action-bar/action-bar-container.tsx
apps/mobile/src/features/balances/bitcoin/bitcoin-balance.tsx
apps/mobile/src/features/balances/stacks/stacks-balance.tsx
apps/mobile/src/features/balances/token-balance.tsx
apps/mobile/src/features/settings/wallet-and-accounts/wallet-card.tsx

This PR:
- re-enables the `ActionBar` (Send / Receive / Swap)
- reverses some text hardcoding (LEA-1780) 
It will be released to a new build for Internal users only and not for the Leatherhood group

Post leatherhood cleanup

---

packages/query/src/bitcoin/stamps/stamps-by-address.query.ts

We have an increased number of alerts coming in as it seems the stamp query has changed to return fewer properties.
Closes #719

fix(query): looser stamps schema

---

packages/models/src/network/network.model.ts

Objects shouldn't really be used for ordering, but order does work, and this _should_ put testnet4 first in our list on the extension (without further changes such as listing them manually, migrating to an array, or writing custom sort logic).

fix: testnet ordering

---

apps/mobile/maestro/flows/accounts-drawer.yaml
apps/mobile/maestro/flows/accounts-page.yaml
apps/mobile/maestro/flows/change-network.yaml
apps/mobile/maestro/flows/change-theme.yaml
apps/mobile/maestro/flows/settings-guides.yaml
apps/mobile/maestro/flows/settings-learn.yaml
apps/mobile/maestro/flows/settings-support.yaml
apps/mobile/maestro/flows/wallet-add-account.yaml
apps/mobile/maestro/flows/wallet-management.yaml
apps/mobile/maestro/flows/wallet-multi-wallet.yaml
apps/mobile/src/features/settings/network-badge.tsx
apps/mobile/src/shared/test-id.ts
packages/ui/src/components/badge/badge.native.tsx

This PR covers adding some basic E2E tests to cover some of the flows we added for the Leatherhood release. 
- Creating / restoring wallets
- Wallet balances for STX/BTC
- Multiple wallet functionality (create / restore multiple wallets, manage and configure those wallets)
- themes
- change networks
- Links to web guides and updated guides for mobile features (mobile guides currently not publicly shown)
We need to add better tests for Biometrics. 
When running tests locally I see we have some fails and I can't see the tests being run in CI (Expo or Github). @edgarkhanzadian do you know where they should be ran?
I had these failures running locally:
```
[Failed] rename-account (1m 7s) (Assertion is false: "testAccount" is visible)
[Failed] change-account-icon (1m 4s) (Element not found: …
```

CI: mobile maestro E2E tests

---

packages/bitcoin/src/p2tr-address-gen.ts

This is a mostly silent change that ought to make our transaction signing more permissive. I suspect that it might be the reason for some PSBT rejections.

fix: make p2tr payments more permissive

---

apps/mobile/src/components/splash-screen-guard/use-auth-state.tsx

This PR fixes a bug we have where:
- As a user with authentication enabled
- When I switch APPS (e.g. from Leather to something else)
- Then I return to Leather 
- It resets the app back to the home screen

fix: remove animation reset that also resets app when switching apps, ref LEA-1792

---

packages/ui/src/components/text/text.native.tsx

Adds a basic hard-coded fix for [LEA-1805](https://linear.app/leather-io/issue/LEA-1805/react-native-text-rendering-issues). This basically adjusts the positioning of the affected text variants within the bounding box without increasing the height of said box. 
Hardcoded adjustment values have been compared with Figma and tested across different Android & iOS devices.
We only have a handful of affected variants at the moment, will re-visit the solution if it's ever necessary.
I've considered two alternatives before going with this one:
1. Patching react-native: cumbersome, will likely require babysitting the patch through future upgrades.
2. Implementing a more complex, theme-aware, animation-aware version of this fix that merges in incoming `paddingTop` & `marginBottom` whether they're …

fix: adjust vertical centering of incorrectly rendered text, closes LEA-1805

---

apps/mobile/maestro/flows/receive.yaml
apps/mobile/maestro/flows/send.yaml
apps/mobile/src/features/send/send-form/loaders/send-form-btc-loader.tsx

This PR allows us to show the send BTC form for zero balance accounts by adding mocks for zero fees. 
I think more work could be needed here but I just wanted to get the form to appear for Leatherhood as previously we are showing an empty screen for zero balance accounts 
https://github.com/user-attachments/assets/18e40a52-3c74-4fa0-9373-95f0a7144842

fix: still show BTC send form for zero balance accounts, ref #LEA-1889

---

packages/rpc/package.json
packages/rpc/src/index.ts
packages/rpc/src/methods/send-transfer.ts
packages/rpc/src/methods/sign-psbt.ts
packages/rpc/src/methods/stx-sign-message.ts
packages/rpc/src/methods/stx-sign-transaction.ts
packages/rpc/src/methods/supported-methods.ts
packages/rpc/src/rpc/schemas.ts
pnpm-lock.yaml

This PR updates the types in our `rpc` package to conform the the _actual_ API running in the `LeatherProvider`

feat: udpate types to conform with extension provider

---

apps/mobile/src/app/(home)/settings/display/index.tsx

This PR removes `Hide Balances` from the `Settings` menu as it's not needed

fix: remove hide balances from settings, ref LEA-1753

---

apps/mobile/src/utils/analytics.ts

Segment event logs in console are enabled by default. Disabling them to declutter the console a little bit. Let me know if there's value in having those on, I can look into trying the setting to an env variable.

Disable segment client console logging

---

apps/mobile/src/components/action-bar/action-bar.tsx

Addresses console warnings about action bar requiring an explicit background color to calculate shadows efficiently.
This component needs a little more attention to match the current designs. Will look into that separately.

Add background to action bar

---

packages/ui/src/components/pressable/pressable.native.tsx

Fixes a bug in Pressable where a noop onLongPress overrides onPress, causing taps to be ignored.

Add conditional handling for onLongPress in Pressable, closes LEA-1888

---

packages/models/src/crypto-assets/crypto-asset-info.model.ts
packages/query/src/bitcoin/stamps/stamps-by-address.hooks.ts

Updates types of SRC-20 tokens to solve https://github.com/leather-io/mono/issues/724 
And then unblock https://github.com/leather-io/extension/pull/6009#issuecomment-2551964027

fix: add src20 image types, ref leather-io/mono#724

---

.env.example
.husky/hooks.js
README.md

* Fix formatting in the README
* Fix the .env.example
* Remove ignored file warnings when eslint is run through lint-staged

Few minor lint setup fixes

---

apps/mobile/src/components/headers/home-header.tsx
apps/mobile/src/features/send/fee-badge.tsx
apps/mobile/src/features/settings/network-badge.tsx
packages/ui/native.ts
packages/ui/src/components/badge/badge.native.stories.tsx
packages/ui/src/components/badge/badge.native.tsx
packages/ui/src/components/badge/badge.web.stories.tsx
packages/ui/src/components/badge/badge.web.tsx
packages/ui/src/components/network-mode-badge/network-mode-badge.web.tsx
packages/ui/src/exports.web.ts

Several small updates to the Tag/Badge component to standardize the naming and the signature between web and mobile versions.
The web version lived under `Tag`, while the mobile was called `Badge`. Going with `Badge` since "tag" carries a slightly different meaning. Will request for the component to be renamed in Figma as well.
* Correct height
* Renamed transparent -> outline
* Correct height
* Added outlined variant
* Made default variant the default
* Removed Pressable. Interactive badges are rare, it's better to add the interactivity at the usage site as necessary.
* Added a story
Pending items to be addressed in a future PR:
* Per-variant Icon colors aren't applied in the web version
* Mobile version is still missing icon support
These depend on the WIP icon system revamp.

Standardize Badge component, closes LEA-1830

---

apps/mobile/maestro/flows/hide-account.yaml
apps/mobile/src/app/(home)/settings/wallet/index.tsx

This PR makes a change to only show the hidden accounts setting if there are hidden accounts 
https://github.com/user-attachments/assets/cd68830b-93bb-4092-877d-1edc578ff972

fix: only show hidden accounts if accounts hidden, ref LEA-1913

---

apps/mobile/src/components/action-bar/action-bar-container.tsx
apps/mobile/src/components/amount-field/amount-field-primary-value.tsx
apps/mobile/src/components/splash-screen-guard/use-auth-context.ts
apps/mobile/src/store/settings/settings.read.ts
packages/bitcoin/src/bitcoin.utils.ts
packages/eslint-config/index.js
packages/query/src/stacks/bns/bns.utils.ts
packages/query/src/stacks/temp-utils.ts
packages/ui/src/components/approver/components/approver-advanced.web.tsx
packages/ui/src/components/collectibles/native/collectible-text.native.tsx
packages/ui/src/components/flag/flag.native.tsx
packages/ui/src/components/highlighting/clarity-prism.shared.ts
packages/ui/src/components/highlighting/highlighter.web.tsx
packages/ui/src/components/highlighting/start-pad.shared.ts
packages/ui/src/utils/style-context.web.tsx
packages/utils/src/spam-filter/spam-filter.ts

Our convention is to [favour function declarations](https://www.notion.so/trustmachines/Function-declarations-22f7055df3124d868a242adb04f0f60d?pvs=4).
This PR enforces this with eslint's [`func-style`](https://eslint.org/docs/latest/rules/func-style) rule.

chore: enforce func-style in eslint

---

packages/query/src/stacks/token-metadata/token-metadata.utils.ts

This pr fixes `Cannot use 'in' operator to search for 'error' in` error

fix: unhandled error in is nft asset condition, LEA-1935

---

packages/query/src/bitcoin/stamps/stamps-by-address.query.ts

fix(query): update stamp schema

---

packages/services/src/balances/btc-balances.service.ts
packages/services/src/balances/constants.ts
packages/services/src/balances/runes-balances.service.ts
packages/services/src/balances/sip10-balances.service.ts
packages/services/src/balances/stx-balances.service.ts
packages/services/src/infrastructure/api/best-in-slot/best-in-slot-api.client.ts

PR fixes an issue that occurs when balance services (BTC, STX, SIP10) are called with fresh app state and/or no wallets loaded (i.e. an empty array of accounts). The balance services should return a default zero balance, instead they throw errors, preventing components from rendering.
The PR also adds logic to skip the BIS xpub inscriptions request when on testnet as it isn't currently supported on the BIS testnet server and is returns a 404. The testnet server will be upgraded end of month and the request can be reinstated.

fix: no wallet balance service calls

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/app/(home)/account/[account]/index.tsx
apps/mobile/src/components/widgets/accounts/accounts-widget.tsx
apps/mobile/src/components/widgets/tokens/tokens-widget.tsx
apps/mobile/src/features/accounts/components/account-balance.tsx
apps/mobile/src/features/balances/bitcoin/bitcoin-balance.tsx
apps/mobile/src/features/balances/bitcoin/runes-balance.tsx
apps/mobile/src/features/balances/stacks/sip10-balance.tsx
apps/mobile/src/features/balances/stacks/stacks-balance.tsx
apps/mobile/src/hooks/use-bitcoin-account-service-requests.ts
apps/mobile/src/queries/balance/runes-balance.query.ts
packages/services/src/balances/sip10-balances.service.spec.ts
packages/services/src/balances/sip10-balances.service.ts
packages/services/src/balances/sip10-balances.utils.spec.ts
packages/services/src/balances/sip10-balances.utils.ts
packages/services/src/index.ts

This PR:
- Integrates the SIP-10 balances service to mobile: LEA-1832
- Adds boiler plate code for Runes: LEA-1981 
I didn't add the icons yet as Tigran will add update icon component to accept URLs LEA-1909
For the `Tokens Widget` we have a hard cap to show only 5 tokens so I added some code to cap it:
- BTC
- STX
- 3 SIP tokens
This is OK for now but we need to revisit this. You can see a demo here:
https://github.com/user-attachments/assets/37cfb782-250d-4015-80ab-3735bb22e830
I did more testing before this cap to make sure we are showing the correct aggregate balances on the homepage:
https://github.com/user-attachments/assets/3bf2cf5e-c6bb-43f8-adc6-21d2c99b7c67

feat: SIP-10 balances on mobile

---

apps/mobile/src/features/send/send-form/sheets/recipient-sheet.tsx

This PR solves a problem with the Send Flow on Android whereby the recipient sheet does not open as there is no set height.

fix: specify sheet height for android, ref LEA-2023

---

apps/mobile/src/features/accounts/account-selector/account-selector-sheet.layout.tsx

Fixes visual regression on Account selector sheet.
Created [an issue](https://linear.app/leather-io/issue/LEA-2086/make-native-sheet-component-composable) to make the native sheet component composable, so we can easily reuse its pre-styled subcomponents in the future.

fix: use correct background color on account sheet, closes LEA-2081

---

apps/mobile/package.json
packages/models/package.json
packages/models/src/types.utils.ts
packages/query/package.json
packages/rpc/package.json
packages/rpc/src/methods/get-addresses.spec.ts
packages/rpc/src/methods/get-addresses.ts
packages/rpc/src/methods/stacks/stx-get-addresses.ts
packages/rpc/src/rpc/schemas.ts
packages/services/package.json
pnpm-lock.yaml

Figuring out best way to handle some message passing and continually running into need to runtime check a payload & narrow the type. This is only possible if **all method requests and response** are available as schemas. I regret setting up this type structure and not going validator first from the start. 
I know we don't follow the convention of "section comments" like I've used here, but find schema heavy files hard to navigate without.
There's a pretty crazy type overload here. The tricky part is that some methods do / do not have params defined. And, based on whether or not a params schema is defined, the inferred type should know whether or not there's a params object. I tried using a conditional type e.g. `TParams extends undefined ? X : Y` but it didn't infer correctly.

fix(rpc): favour zod types only

---

packages/query/src/stacks/leather-headers.ts
packages/services/src/infrastructure/api/hiro/hiro-leather-headers.ts

[Per conversation on Slack](https://trustmachines.slack.com/archives/C05T570TNQJ/p1738072807669179), Charlie recommended updating our identifying HTTP headers.
Would be great to avoid code duplication like this, if possible.

fix: update hiro api headers

---

apps/mobile/ios/Podfile.lock
apps/mobile/package.json
apps/mobile/src/components/headers/animated-header/animated-header-screen-with-keyboard.layout.tsx
apps/mobile/src/components/headers/animated-header/animated-header-screen.layout.tsx
apps/mobile/src/components/headers/animated-header/animated-header.hooks.tsx
apps/mobile/src/components/headers/animated-header/animated-title-header.tsx
apps/mobile/src/components/headers/header.layout.tsx
pnpm-lock.yaml

Adds a blur effect to animated headers, and fixes animated title being invisible for a short amount of time while scrolling up.
https://github.com/user-attachments/assets/f324e96b-a164-404b-99e2-ce1d264ae19e
https://github.com/user-attachments/assets/f25719ef-a9f3-4016-aeaa-3b2ef45712e7

Add "blur" effect to animated headers, closes LEA-1911

---

packages/rpc/src/methods/open-swap.ts
packages/rpc/src/methods/stacks/stx-sign-transaction.ts
packages/rpc/src/methods/stacks/stx-transfer-sip10-ft.ts
packages/rpc/src/methods/stacks/stx-transfer-stx.ts
packages/rpc/src/methods/stacks/stx-update-profile.ts

Minimising use of `RpcRequest` and `RpcResponse`

fix(rpc): use more consistent schema definitions

---

packages/bitcoin/src/bitcoin-signer.ts
packages/rpc/package.json
packages/rpc/src/index.ts
packages/rpc/src/methods/bitcoin/send-transfer.ts
packages/rpc/src/methods/bitcoin/sign-message.ts
packages/rpc/src/methods/bitcoin/sign-psbt.ts
packages/rpc/src/methods/get-addresses.ts
packages/rpc/src/methods/get-info.ts
packages/rpc/src/methods/open-swap.ts
packages/rpc/src/methods/open.ts
packages/rpc/src/methods/stacks/_stacks-helpers.ts
packages/rpc/src/methods/stacks/stx-call-contract.ts
packages/rpc/src/methods/stacks/stx-deploy-contract.ts
packages/rpc/src/methods/stacks/stx-get-addresses.ts
packages/rpc/src/methods/stacks/stx-sign-message.spec.ts
packages/rpc/src/methods/stacks/stx-sign-message.ts
packages/rpc/src/methods/stacks/stx-sign-structured-message.ts
packages/rpc/src/methods/stacks/stx-sign-transaction.ts
packages/rpc/src/methods/stacks/stx-transfer-sip10-ft.ts
packages/rpc/src/methods/stacks/stx-transfer-stx.ts
packages/rpc/src/methods/stacks/stx-update-profile.ts
packages/rpc/src/methods/supported-methods.ts
packages/rpc/src/rpc/helpers.ts
packages/rpc/src/rpc/schemas.ts
packages/utils/package.json
packages/utils/src/index.ts
pnpm-lock.yaml

This PR refactors the RPC package and introduces a new way of defining RPC endpoints.
One might assume defining a library of RPC endpoints would be trivial but it really hasn't been. Thus far we've iterated from type-first definitions, to a schema-first definitions with types inferred. Using zod schemas solved a problem of being able to turn `any` message into a runtime checked strongly typed payload. However, with no unified way of defining endpoints, we were running to constant issues with slight variations in how we export the schemas and types.
Here I introduce ~two~ one method `defineRpcEndpoint` ~and `defineParameterlessRpcEndpoint`~.
I'd love to have had 1 method with an optional `params` property. I tried getting this to work with conditional generic types, but to do this and make …

refactor(rpc): use consistent define method

---

packages/rpc/src/methods/stacks/stx-transfer-sip10-ft.ts

Need the `baseStacksTransactionConfigSchema` added for use in the extension.

fix: stx transfer sip10 ft types

---

packages/rpc/src/methods/stacks/stx-transfer-sip10-ft.ts

Missed I needed to add the intersection.

fix: add zod intersection to type

---

packages/rpc/package.json
packages/rpc/src/index.ts
packages/rpc/tsup.config.ts

This PR includes two changes:
1) `commonjs` build output for RPC package. I'm hoping this fixes the fact that in regular codesandboxes it doesn't find the types. In their "devboxes" it works as expected currently.
2) Inferred types for `params` object for our `RequestFn`. I thought we had this already but apparently not.

feat(rpc): commonjs output, fixes params type issue

---

packages/constants/src/index.ts
packages/services/src/index.ts
packages/services/src/infrastructure/api/best-in-slot/best-in-slot-api.client.ts
packages/services/src/infrastructure/api/best-in-slot/best-in-slot-api.utils.spec.ts
packages/services/src/infrastructure/api/best-in-slot/best-in-slot-api.utils.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.client.ts
packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/api/leather/leather-api.pagination.ts
packages/services/src/infrastructure/api/leather/leather-api.schemas.ts
packages/services/src/infrastructure/settings/settings.selectors.spec.ts
packages/services/src/infrastructure/settings/settings.selectors.ts
packages/services/src/inversify.config.ts
packages/services/src/transactions/bitcoin-transactions.service.ts
packages/services/src/transactions/bitcoin-transactions.utils.spec.ts
packages/services/src/transactions/bitcoin-transactions.utils.ts
packages/services/src/utxos/utxos.service.ts
packages/services/src/utxos/utxos.utils.spec.ts
packages/services/src/utxos/utxos.utils.ts

This PR uses bitcoin transaction data from our API to determine / map outbound UTXOs, which are then used to calculate outbound BTC balance.
The incorporation of outbound balances (i.e. subtraction from available balance), might cause UX issues [described further here](https://www.notion.so/trustmachines/Mobile-BTC-Balance-UX-Issue-1a0d74b694c780329bc9f73cbeff7448?pvs=4). May need to migrate to using an alternative balance type in mobile UI balance components.
The PR also fixes the issue with BTC balances not appearing on testnet4.

feat: implement btc outbound balance, closes LEA-1808, fixes LEA-2129

---

packages/models/src/network/network.model.ts

I believe this is the correct url for testnet now, it can be double checked here:
https://trustmachines.slack.com/canvas/C07GNE28RE1
**Testing this change now locally**

fix: update sbtc bitcoin url

---

packages/models/src/network/network.model.ts

This change now seems incorrect, so reverting.
Reverts leather-io/mono#896

Revert "fix: update sbtc bitcoin url"

---

packages/bitcoin/src/bip322/sign-message-bip322-bitcoinjs.ts
packages/bitcoin/src/coin-selection/calculate-max-spend.ts
packages/bitcoin/src/psbt/psbt-details.ts
packages/bitcoin/src/psbt/psbt-inputs.ts
packages/bitcoin/src/psbt/psbt-outputs.ts
packages/bitcoin/src/psbt/psbt-totals.ts
packages/bitcoin/src/signer/bitcoin-signer.ts
packages/bitcoin/src/utils/bitcoin.utils.ts
packages/bitcoin/src/utils/lookup-derivation-by-address.ts
packages/bitcoin/src/validation/bitcoin-address.ts
packages/bitcoin/src/validation/transaction-validation.ts
packages/models/src/crypto-assets/bitcoin/bitcoin.model.ts
packages/models/src/index.ts
packages/query/src/bitcoin/ordinals/brc20/brc20-tokens.query.ts

This PR moves the `BitcoinAddress` branded type to the models package as when installing it in the extension I was hitting issues with interface Inscription and Utxo trying to apply my types.
If you try and install the bitcoin package to models you hit circular dependency issues.
I should have tested my original work better inside of the extension first

chore: move BitcoinAddress to models to avoid circular dependency

---

packages/query/src/common/remote-config/remote-config.query.ts
packages/query/src/common/remote-config/remote-config.types.ts
packages/query/src/stacks/fees/fees.hooks.ts
packages/query/src/stacks/fees/fees.utils.spec.ts
packages/query/src/stacks/fees/fees.utils.ts

This pr changes logic of fee estimation for contract calls and deployment. we set min/max default fee values and compare it to those from hiro api, so:
if hiro estimation is in range of min/max defaults or less than min default - we choose hiro fee
if hiro estimation is more than max default - we choose hiro fee only in case of high fee type
if hiro estimation is less than min default - we choose hiro fee only in case of low fee type

feat: change fee estimation logic, LEA-1760

---

packages/provider/src/add-leather-to-providers.ts
packages/rpc/src/index.ts
packages/rpc/src/methods/stacks/stx-transfer-sip9-nft.ts

Need these for the last issue in the extension for SIP-30 requests.

fix: add rpc types for sip9 transfers

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/features/send/send-form/hooks/use-send-form-btc.tsx
apps/mobile/src/features/send/send-form/hooks/use-send-form-stx.tsx
apps/mobile/src/features/send/send-form/loaders/send-form-btc-loader.tsx
apps/mobile/src/features/send/send-form/validation/btc.validation.ts
apps/mobile/src/features/send/send-form/validation/stx.validation.ts
packages/bitcoin/src/coin-selection/calculate-max-spend.ts
packages/bitcoin/src/validation/amount-validation.spec.ts
packages/bitcoin/src/validation/amount-validation.ts
packages/bitcoin/src/validation/bitcoin-error.ts
packages/bitcoin/src/validation/transaction-validation.spec.ts
packages/bitcoin/src/validation/transaction-validation.ts
packages/models/src/index.ts
packages/models/src/transactions/transaction-error.model.ts
packages/stacks/src/validation/stacks-error.ts
packages/stacks/src/validation/transaction-validation.spec.ts
packages/stacks/src/validation/transaction-validation.ts
packages/utils/src/money/index.ts
packages/utils/src/money/is-valid-precision.spec.ts
packages/utils/src/money/is-valid-precision.ts

This PR adds precision validation to `STX` and `BTC` transactions and fixes a bug with minimum BTC spend amount
https://github.com/user-attachments/assets/5ddd566b-78aa-4094-9739-a7c0d5664fb1

chore: add precision checks to stacks and btc

---

.github/workflows/release-please.yml

This PR downgrades `release-please` to try and fix issues with releasing monorepo packages. 
It was upgrade in [this PR](https://github.com/leather-io/mono/pull/878/files#) but is causing some [build issues ](https://trustmachines.slack.com/archives/C05LAP952E7/p1740424072409059)

fix: rollback release-please action

---

turbo.json

Removes Turbo warnings where there are no outputs for web or mobile

ci: fix turbo missing output warnings

---

packages/rpc/src/rpc/helpers.ts

Was a little too optimising in creating this wrapper fn and actually need the untyped methods themselves in some cases

fix: export methods individually

---

apps/mobile/src/app/(home)/settings/display/index.tsx
apps/mobile/src/components/balance/balance.tsx
packages/utils/src/money/format-money.spec.ts
packages/utils/src/money/format-money.ts

This PR:
- exposes the currency change setting to all users
- updates `i18nFormatCurrency` to allow for non-USD currencies
To test:
- change the currency in app settings
- observe balances updating to the correct precision and using the correct currency symbol
Demo:
https://github.com/user-attachments/assets/835e488e-c9cc-4961-a2a6-7483f45ac583

fix: specify currency symbol and precision using currency map

---

eslint.config.js
packages/rpc/src/index.ts
packages/sdk/README.md
packages/sdk/package.json
packages/sdk/src/client.spec.ts
packages/sdk/src/client.ts
packages/sdk/src/index.ts
packages/sdk/tsconfig.json
packages/sdk/tsup.config.ts
packages/sdk/vitest.config.js
pnpm-lock.yaml
release-please-config.json

This work builds on the [RPC refactor](https://github.com/leather-io/mono/pull/866) and a conversation with @fbwoolf and @markmhendrickson.
Currently, we only publish RPC types and schemas to developers. With a clean object of known methods, it's fairly straightforward to generate a JS client with methods users can call, which is an improvement on having to access the provider directly from the global object. Parameter and result types are inferred from the RPC spec.
How much we want to expand and maintain this it still in question. Perhaps few will use this, in favour of connect or other wallet wrapping libraries. But, at least in its current bare bones state, it'd be minimal effort to maintain, and might be an interesting package to publish, even if only used for internal use, or …

feat(sdk): leather sdk

---

packages/rpc/src/methods/bitcoin/send-transfer.ts

More permissive schema for sendTransfer endpoint. This aids interaction with Leather for those that just want to consume the APIs. 
Improves support for SIP30/Stacks connect.

fix(rpc): send transfer, closes LEA-2248

---

packages/rpc/src/index.ts
packages/rpc/src/methods/stacks/stx-get-networks.ts

This PR adds one of the remaining schema definitions for SIP-30, `getNetworks`.
See SIP definition here https://github.com/janniks/sips/blob/main/sips/sip-030/sip-030-wallet-interface.md#method-stx_getnetworks

feat(rpc): add stx_getNetworks

---

.github/workflows/check-linear-merge-pr.yml
.github/workflows/check-linear-merge.yml

This CI job should check whether the PR in a merge queue can be merged with Git's `--ff-only` command. It should allow us to change to the _Merge_ strategy, while retaining linear commits.
**Motivation for these changes**
@camerow has added org rulesets that enforce [GPG signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
Our existing merge pattern uses the _Rebase_ strategy, to ensure linear atomic commits, and avoiding superfluous merge commit messages. Rebasing causes the commit hash to change, thus invalidating any signature.
Github has limitation that you cannot Rebase, then Merge with `--ff-only`. As such, a combination of branch rules and custom actions should* be possible to be used to achieve the same behaviours with …

ci: ensure linear merge

---

packages/stacks/src/signer/signer.ts

I accidentally used `refactor` in my commit msg, so using this to add the Stacks pkg change to the release PR.

fix: stacks pkg release

---

.github/workflows/crowdin-action.yml

This repo's CI has been broken for months. These Github actions run only on dev, not pull requests, so developers have no idea if they'll break `dev` before merging. 
Until these are fixed, and ran on pull requests, there is no point having them enabled

ci: disable broken jobs

---

packages/services/src/balances/runes-balances.service.ts
packages/services/src/balances/sip10-balances.service.spec.ts
packages/services/src/balances/sip10-balances.service.ts
packages/services/src/balances/sip10-balances.utils.ts

Adds improved error handling to SIP10 and Runes balance services that prevent top-level failures of account and total balance service calls when any individual token balance lookup fails (e.g. failures during asset info + market data fetching).
This fixes a bug preventing the display of sip10 tokens and the incorrect summing of total balance.
PR also adds:
* Filtering of SIP10 token lists to remove zero-balance tokens. 
* Sort function to order SIP10 and Runes token balance lists by available fiat value.

fix: sip10 balance service error handling

---

packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/settings/settings.selectors.ts

Fixes a bug in fetching testnet BTC transactions via the `LeatherApiClient`. 
The client was incorrectly using the "BitcoinNetworkMode" setting, which consolidates testnet network IDs into "testnet", while the API expects the network parameter to distinguish b/t "testnet3" and "testnet4".
The PR implements a selector for the "BitcoinNetwork" setting and uses it when fetching BTC transactions.

fix: leather api fetch using correct bitcoin network setting

---

apps/web/app/components/external-link.tsx
apps/web/app/components/page.tsx
apps/web/app/layouts/footer/footer.layout.tsx
apps/web/app/layouts/footer/footer.tsx
apps/web/app/layouts/nav/nav.tsx
apps/web/app/pages/earn/earn.tsx
apps/web/app/pages/home/home.tsx
apps/web/app/root.tsx
apps/web/panda.config.ts
apps/web/vite.config.ts
packages/tokens/src/typography.ts

This PR adds a footer to the web app. I added the bare minimum responsiveness to make it not completely useless at smaller sizes. 4 columns breaks to 2 etc. I've used the compound component pattern with layout components to make the resulting `AppFooter` component at clean as possible, and focused entirely on content (and functionality if any added later). For example, adding Crownin translations to the footer will be trivial, compared to if content were spread throughout various layout components. Note that subscribe to newsletter functionality not included in this work.
I had to make some small fixes to nav as I had never made it position fixed.
Thanks @mica000 for making it beige. I think it looks better, and was easier to build 🙏🏼
**Screenshot**
**Recording** …

feat(web): site footer

---

apps/mobile/src/app/(home)/settings/index.tsx
apps/mobile/src/hooks/use-copy-to-clipboard.ts
apps/mobile/src/hooks/use-device-id.ts

Adds a copiable device ID to settings screen. This will let testers share their ID to get access to in-progress features.

feat(mobile): add device id to settings

---

apps/web/app/components/icons/bitcoin-icon.tsx
apps/web/app/components/icons/stacks-icon.tsx
apps/web/app/components/table.tsx
apps/web/app/pages/earn/components/earn-provider-table.tsx
apps/web/vite.config.ts

This is a small PR that improves upon some of the table styling pushed in my last PR. I've made some new icon components here, which I'd rather not do since they exist in UI lib, but they're not working with SSR, and haven't investigated thoroughly why yet cc/ @tigranpetrossian.
The designs have nicely space columns which are hard to replicate in HTML tables. Right aligning a column next to a left aligned column creates very tightly margin with vast whitespace the other side. I'm hacking this, while keeping right alignment, using transform to just shift negatively across x axis.
The actual icons are in @alter-eggo's PR hence mock icon here, they can be added when his work is merged.

feat(web): table improvements

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/features/approver/components/fees/base-fee-card.tsx
apps/mobile/src/features/approver/components/fees/base-fee-option.tsx
apps/mobile/src/features/approver/components/fees/bitcoin-fee-option.tsx
apps/mobile/src/features/approver/components/fees/bitcoin-fee-sheet.tsx
apps/mobile/src/features/approver/components/fees/stacks-fee-option.tsx
apps/mobile/src/features/approver/components/fees/stacks-fee-sheet.tsx
apps/mobile/src/features/approver/components/inputs-outputs-card.tsx
apps/mobile/src/features/approver/components/utxo-row.tsx
apps/mobile/src/features/approver/utils.tsx

To prevent future confusion, replacing occurrences of `usd` with `fiat` where appropriate in approver. The values were already correctly converted and formatted, but marked as `usd` in variable names for historical reasons.
While at it, also simplified some object lookups, and replaced occurrences of `balance` with `amount` for fees and Utxos, as those amounts technically aren't balances.

refactor: approver naming improvements, closes LEA-2349

---

.github/workflows/mobile-preview-builds.yml

Rename `needs:demo-build` to `build:mobile:simulator` to avoid PRs being blocked by `needs:*` prefix.

chore: rename needs:demo-build label

---

apps/mobile/src/features/approver/components/fees/base-fee-option.tsx
apps/mobile/src/features/approver/components/fees/bitcoin-fee-sheet.tsx
apps/mobile/src/features/approver/components/fees/fee-sheet.layout.tsx
apps/mobile/src/features/approver/components/fees/stacks-fee-sheet.tsx
apps/mobile/src/features/psbt-signer/psbt-signer.tsx
apps/mobile/src/features/stacks-tx-signer/stacks-tx-signer.tsx

Adds auto-closing and a confirmation toast to fee selection in the Approver flow.
https://github.com/user-attachments/assets/52994d3e-db9b-4b99-867e-6aefd385a092

fix(mobile): collapse the sheet and show toast on fee selection in approver, closes LEA-2022

---

apps/web/app/app.tsx
apps/web/app/constants.ts
apps/web/app/constants/environment.ts
apps/web/app/queries/stacks/stacks-client.ts
apps/web/app/root.tsx
apps/web/app/store/stacks-network.ts
apps/web/app/types/network.ts
apps/web/package.json
apps/web/vite.config.ts
apps/web/wrangler.toml
packages/query/package.json
packages/services/package.json
pnpm-lock.yaml

This pr 
- adds tanstack query lib/provider
- adds vite-plugin-node-polyfill
- updated wrangler bc of this [err](https://github.com/leather-io/mono/actions/runs/13988601288/job/39167244719)
- upgrades alex-sdk library, otherwise get err with stacks/transaction lib (on the screenshot)

feat: add query provider and upgrade alex sdk package

---

packages/query/src/stacks/hiro-api-types.ts
packages/query/src/stacks/stacks-client.ts

I am thinking we can use this type now looking at `fetchAbi` from `@stacks/transactions`:
https://github.com/hirosystems/stacks.js/blob/654ca25a5993005ddbb6869376ea03cfb95ce131/packages/transactions/src/fetch.ts#L261

fix: contract interface query response type

---

.github/workflows/crowdin-action.yml
apps/mobile/package.json
pnpm-lock.yaml

This PR is re-adding `crowdin-action.yml`. 
- I incorrectly approved it to be disabled [here](https://github.com/leather-io/mono/pull/956)
- I also even recommended totally deleting it [here](https://github.com/leather-io/mono/pull/961)
This was a mistake as now I have realised that new keys added during development aren't syncing and creating new IDs in Crowdin. 
I'll keep refining this process but for now we need this to run and sync keys on merge to `dev`.

fix: re-add crowdin action and update crowdin

---

.github/workflows/release-please.yml
.github/workflows/update-mobile-versions.yml

This PR builds on @pete-watters original closed PR. I've generated a GPG key [`6E3BD917`](https://keys.openpgp.org/search?q=625A20754D875161) and passphrase, and added these as org secrets.
First we import the GPG key, then use the `signoff` flag of release please, which'll (hopefully) sign with the imported key.

ci: sign off release pr commit

---

packages/rpc/src/methods/open.ts

Allows additional props to not cause the schema to fail. 
Really just trying to trigger release.

fix(rpc): allow unknown props in open method

---

.github/workflows/release-please.yml
.github/workflows/sign-release-commit.yml

I think I've been caught out by issue where if default `GH_TOKEN` does something, it doesn't trigger CI https://github.com/orgs/community/discussions/55906#discussioncomment-5946239
I've added the token to the checkout action, if this still doesn't run, I'll try manually triggering the action

ci: run --gpg-sign on release branch

---

apps/mobile/index.js
apps/mobile/ios/Podfile.lock
apps/mobile/package.json
packages/query/package.json
packages/services/package.json
packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/inversify.config.ts
pnpm-lock.yaml

Adds an ID to Leather API requests.
Upgrades the `uuid` package in mono (`mobile`, `@leather.io/services`, `@leather.io/query`) to `v11.1.0`. The updated version no longer relies on a separate types import.
Followed the `uuid` package [guide for React Native](https://www.npmjs.com/package/uuid#react-native--expo) to import the recommended `crypto.getRandomValues` polyfill.

feat: add client id to leather api reqs

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/services/init-app-services.ts
packages/services/src/index.ts
packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/environment.ts
packages/services/src/inversify.config.ts
packages/services/src/inversify.types.ts

Refactored the services layer to accept a more generic "Environment" option for Leather API url switching (prod vs staging).
Also, didn't realize we had set up the NODE_ENV variable already (`EXPO_PUBLIC_NODE_ENV`). This is actually the more-appropriate way of environment signalling, so this refactors to use this over the more ambiguous "WALLET_ENVIRONMENT".

refactor: use node env for api url switching

---

.github/workflows/release-please.yml

Mobile builds were being triggered for all releases. This PR removes that overzealous behavior and we plan to enhance our mobile CI with a number of improvements in the coming weeks getting ready for release.

ci: remove mobile releasing from release-please, closes ENG-2

---

apps/mobile/src/app/_layout.tsx

Fixes a regression introduced in #1026 making `useGlobalSheets` inaccessible from within sheets because of incorrect provider order.

fix(mobile): fix sheet provider order

---

.github/workflows/playwright.yml

Skip Playwright runs when changes are only in *.native.* files in `ui`, since those don’t affect web.

chore: exclude ui "*.native" files from playwright workflow

---

.dependency-cruiser.cjs
apps/web/app/app.tsx
apps/web/app/features/sbtc-enroll/sbtc-enroll-button.tsx
apps/web/app/features/sbtc-enroll/use-enroll-transaction.ts
apps/web/app/features/sign-in-button/sign-in-button.tsx
apps/web/app/features/stacking/components/choose-pooling-amount.tsx
apps/web/app/features/stacking/providers/stacking-client-provider.tsx
apps/web/app/features/stacking/start-pooled-stacking.tsx
apps/web/app/helpers/utils.ts
apps/web/app/pages/sbtc-rewards/components/acquire-sbtc-grid.tsx
apps/web/app/pages/sbtc-rewards/components/sbtc-hero-card.tsx
apps/web/app/pages/sbtc-rewards/components/sbtc-protocol-reward-grid.tsx
apps/web/app/pages/sbtc-rewards/sbtc-rewards-context.tsx
apps/web/app/pages/sbtc-rewards/sbtc-rewards.tsx
apps/web/app/store/addresses.ts
packages/ui/src/components/tooltip/tooltip.web.tsx

This PR adds functionality to the sBTC rewards page. Pulling over the enroll contact call from earn. The other buttons are links to the respective websites.

feat(web): sBTC enroll functionality, closes LEA-2456

---

apps/mobile/src/app/account/[account]/account.layout.tsx
apps/mobile/src/app/account/[account]/balances.tsx
apps/mobile/src/app/account/[account]/collectibles.tsx
apps/mobile/src/app/balances/index.tsx
apps/mobile/src/app/collectibles/index.tsx
apps/mobile/src/app/create-new-wallet.tsx
apps/mobile/src/app/hardware-wallets.tsx
apps/mobile/src/app/mpc-wallets.tsx
apps/mobile/src/app/secure-your-wallet.tsx
apps/mobile/src/app/settings/display/index.tsx
apps/mobile/src/app/settings/help/index.tsx
apps/mobile/src/app/settings/index.tsx
apps/mobile/src/app/settings/networks/index.tsx
apps/mobile/src/app/settings/security/index.tsx
apps/mobile/src/app/settings/wallet/configure/[wallet]/[account]/index.tsx
apps/mobile/src/app/settings/wallet/configure/[wallet]/view-secret-key.tsx
apps/mobile/src/app/settings/wallet/hidden-accounts.tsx
apps/mobile/src/app/settings/wallet/index.tsx
apps/mobile/src/components/action-bar/action-bar-container.tsx
apps/mobile/src/components/headers/components/header-options.tsx
apps/mobile/src/core/app-navigation-stack.tsx
apps/mobile/src/features/balances/utils/get-chain-layer-from-protocol.ts
apps/mobile/src/features/receive/receive-sheets/get-assets.ts
apps/mobile/src/features/receive/receive-sheets/select-account.tsx
apps/mobile/src/features/receive/receive-sheets/select-asset.tsx
apps/mobile/src/features/send/screens/form.tsx
apps/mobile/src/features/send/screens/select-account.tsx
apps/mobile/src/features/send/screens/select-asset.tsx

This PR bundles together a few fixes and improvements in the mobile app:
- show home activity icon in all builds, ref [PRO-25](https://linear.app/leather-io/issue/PRO-25/activity-icon-not-appearing-on-home-page)
- allow users to access account settings from account page, ref [PRO-17](https://linear.app/leather-io/issue/PRO-17/make-it-easier-to-change-account-settings)
- add new key for Stacks layer 2, ref [PRO-23](https://linear.app/leather-io/issue/PRO-23/labeling-layer-1-vs-layer-2-stacks)
- go to account page on press of account card on settings
- add text labels to action bar and sheet headers, ref [PRO-13](https://linear.app/leather-io/issue/PRO-13/send-receive-buy-swap-is-not-overly-intuitive-like-it-is-on-the-ext)
-  change backup text to remove collectibles, ref …

chore: mobile bug fixes

---

apps/web/tests/sbtc-rewards.spec.ts

This PR adds a Playwright test for the sBTC Rewards page. The test verifies that:
- The page loads correctly
- Key headings and content are visible
- Navigation elements are present
- Protocol information sections are displayed properly
This test will ensure that the sBTC Rewards page continues to render correctly as the codebase evolves.

test(web): add basic test for sBTC Rewards page

---

packages/ui/src/components/approver/components/approver-advanced.native.tsx

Fixes a small cosmetic issue mentioned in: [LEA-2468: Fix Chevron icon size in Approver](https://linear.app/leather-io/issue/LEA-2468/fix-chevron-icon-size-in-approver)
762b-4063-96d0-994e37782b01"/>

fix(ui): fix chevron size in approver-advanced.native.tsx, closes LEA-2468

---

apps/mobile/src/features/send/screens/select-account.tsx

Fixes a bug with displaying irrelevant accounts with 0 balances after selecting an asset in the Send flow.
The "Select account" will now display only accounts with holdings in selected asset, with balance narrowed to the selected asset.
https://github.com/user-attachments/assets/5d059ebb-650a-4c7b-b0fd-08b69d06e338

fix(mobile): filter account selection by selected asset, closes PRO-32

---

apps/mobile/src/features/accounts/components/account-address.tsx
apps/mobile/src/hooks/use-account-display-address.ts
apps/mobile/src/store/settings/settings.read.ts

Addresses displayed on various account items are currently based on a user preference. This PR adds an ability to override the preference for cases when we need a narrower context, e.g. show Stacks address in STX send form, or taproot address when an transaction item resolving to an account was made to/from taproot account.

feat(mobile): add display preference override to account address

---

apps/mobile/src/app/account/[account]/account-overview-card.tsx
apps/mobile/src/app/settings/wallet/configure/[wallet]/[account]/choose-avatar.tsx
apps/mobile/src/features/accounts/components/account-avatar.tsx
apps/mobile/src/features/accounts/components/account-card.tsx
apps/mobile/src/features/settings/choose-avatar/avatar-button.tsx
apps/mobile/src/features/settings/choose-avatar/avatars.tsx
apps/mobile/src/store/accounts/accounts.write.ts
apps/mobile/src/store/accounts/utils.ts
apps/mobile/src/store/utils.ts

Adds random icon selection when creating accounts. Rules:
1. First account in the first wallet account gets "sparkles"
2. Picks unused icon across wallets when possible
3. Always avoids repeating the preceding icon
https://github.com/user-attachments/assets/dc64eda3-a113-49d1-a921-f8fe2f043b46
I also started writing tests for the accounts slice (including this feature). but there's only so much time I can spend on that with more pressing tasks at hand. Will find some time for a followup PR--definitely worth having decent coverage for the slice.

feat(mobile): add account icon randomization, closes LEA-1790

---

apps/mobile/src/features/send/components/recipient/v2/build-recipient-suggestions.spec.ts
apps/mobile/src/features/send/components/recipient/v2/build-recipient-suggestions.ts
apps/mobile/src/features/send/components/recipient/v2/recipient-selector/recipient-selector-header.tsx
apps/mobile/src/features/send/components/recipient/v2/recipient-selector/recipient-selector-search-empty-state.tsx
apps/mobile/src/features/send/components/recipient/v2/recipient-selector/recipient-selector.tsx
apps/mobile/src/features/send/components/recipient/v2/recipient-toggle.tsx
apps/mobile/src/features/send/components/recipient/v2/recipient.utils.ts
apps/mobile/src/features/send/components/recipient/v2/use-recipient-suggestions.ts

Adds empty state view when searching for address, and better handling of query states.
Sneaking in a small case-sensitivity bugfix too, along with moving some helpers around.

feat(mobile): add search empty state to the recipient flow

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/features/send/components/recipient/v2/build-recipient-suggestions.spec.ts
apps/mobile/src/features/send/components/recipient/v2/build-recipient-suggestions.ts
apps/mobile/src/features/send/components/recipient/v2/recipient-selector/recipient-selector-item.tsx
apps/mobile/src/features/send/components/recipient/v2/recipient.utils.ts
apps/mobile/src/features/send/components/recipient/v2/types.ts
apps/mobile/src/features/send/components/recipient/v2/use-recipient-suggestions.ts
packages/bitcoin/src/validation/address-validation.ts
packages/stacks/src/validation/address-validation.ts

**Adds relative date to recent suggestions:**
1. Correct recents order.
2. Pass correct validation helper for searching
3. Remove extra checks from address validation primitives to avoid false positives.

Add timestamp to recipient recents, + few fixes

---

apps/mobile/src/components/headers/components/header-options.tsx
apps/mobile/src/features/receive/receive-sheets/receive-asset-details.tsx
apps/mobile/src/features/receive/receive-sheets/receive-asset-item.tsx
packages/ui/src/components/icon-button/icon-button.native.tsx

Updates the existing, but barely used `icon-button.native.tsx` to match the designs and offer screen reader accessibility.
* Add required `label` prop mapping to `accessibilityLabel` internally
* Update the single usage point in the mobile app
* Replace header action buttons implementations with IconButton with added a11y labels
No visual updates. 
There are more qualifying usages in the app that should be refactored to use this, will do in a follow-up PR later([tracked here](https://linear.app/leather-io/issue/LEA-2544/use-the-iconbutton-component-for-relevant-features-in-the-mobile-app)), because of time constraints.

feat(mobile): update native icon button

---

apps/web/app/components/pool-overview.tsx
apps/web/app/features/stacking/components/stacking-layout.tsx
apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx
apps/web/app/pages/stacking/pooled-stacking.tsx

This pr adds pool overview component on pooled stacking page 
Data is hardcoded there for now, investigating how can get it 
https://github.com/user-attachments/assets/5e1c127d-17a5-42d3-b5c4-221576c24715

feat(web): add pool overview component on pooled stacking page

---

apps/mobile/eas.json

Build ios app with xcode 16 on EAS servers with ios 18.
should fix this:
```
ITMS-90725: SDK version issue - This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution.
```

fix: build ios app on xcode 16

---

apps/mobile/ios/Podfile.lock
apps/mobile/src/app/account/[account]/balances.tsx
apps/mobile/src/app/account/[account]/collectibles.tsx
apps/mobile/src/app/account/[account]/index.tsx
apps/mobile/src/app/balances/index.tsx
apps/mobile/src/app/collectibles/index.tsx
apps/mobile/src/app/home/home.tsx
apps/mobile/src/features/account/account-selector/account-selector-sheet-header.tsx
apps/mobile/src/features/account/account.tsx
apps/mobile/src/features/account/accounts-widget.tsx
apps/mobile/src/features/account/components/account-overview-card.tsx
apps/mobile/src/features/activity/activity-widget.tsx
apps/mobile/src/features/activity/activity.layout.tsx
apps/mobile/src/features/approver/components/fees/base-fee-card.tsx
apps/mobile/src/features/balances/balances-widget.tsx
apps/mobile/src/features/collectibles/collectibles-widget.tsx
apps/mobile/src/features/feature-flags/index.ts
apps/mobile/src/features/settings/network-badge.tsx

This PR batches together some small and easy mobile fixes:
- feature flag `FeeBadge` until its calculated dynamically [PRO-77](https://linear.app/leather-io/issue/PRO-77/enable-or-remove-congestion-label-in-send-flow-of-mobile-app)
- make some copy changes [LEA-2595]([LEA-2595](https://linear.app/leather-io/issue/LEA-2595))
- add wallet name to account page [LEA-2497]([LEA-2497](https://linear.app/leather-io/issue/LEA-2497))
- adjust padding of network label and settings cog [LEA-2471](https://linear.app/leather-io/issue/LEA-2471/fix-padding-with-the-right-icon-and-testnet-label-in-the-header)
https://github.com/user-attachments/assets/3692d247-80e3-4ddd-82a2-1600caf87c91

chore: miscellaneous small fixes

---

apps/mobile/src/components/amount-field/amount-field-primary-value.tsx
apps/mobile/src/components/amount-field/amount-field.utils.ts
apps/mobile/src/features/send/constants.ts
apps/mobile/src/features/send/forms/btc/btc-form.tsx
apps/mobile/src/features/send/forms/stx/stx-form.tsx
apps/mobile/src/features/send/temporary-constants.ts
packages/ui/src/components/numpad/numpad.native.stories.tsx
packages/ui/src/components/numpad/numpad.native.tsx

Enabling locallization without [Standardize Balances Formatting](https://linear.app/leather-io/project/standardize-balances-formatting-e8bf0300f9b5) in place made the formatting incosistent.
This PR is a cleanup for relevant code, in preparation to do it one the project above is implemented:
* Numpad now accepts an optional decimal separator instead of a locale, since we can retrieve the separator form`react-native-localize` 
* Primary value formatting is removed for the time being
Added a [new issue](https://linear.app/leather-io/issue/LEA-2610/enable-localization-in-send-form) to track this.

refactor(mobile): clean up Send localization logic, closes LEA-2375

---

apps/web/app/components/explainer.tsx
apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-action-buttons.tsx
apps/web/app/features/stacking/pooled-stacking-info/use-revoke-delegate-stx.ts
apps/web/app/features/stacking/user-positions.tsx

This PR adds the new dropdown with actions to the active pooling row, utilising the same logic from the active stacking page.
Liquid stacking remains unchanged.

feat(web): add pooling actions dropdown, closes ENG-76

---

apps/mobile/src/features/feature-flags/index.ts

Removing a leftover flag reference for recipient flow.

refactor(mobile): remove the recipient flag hook

---

apps/web/app/constants/default-meta-tags.ts
apps/web/app/data/content.ts
apps/web/app/features/sign-in-button/sign-in-button.tsx
apps/web/app/features/stacking/direct-stacking-info/components/liquid-stacking-action-buttons.tsx
apps/web/app/features/stacking/increase-liquid-stacking/increase-liquid-stacking.tsx
apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-action-buttons.tsx
apps/web/app/features/stacking/start-liquid-stacking/start-liquid-stacking.tsx
apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx
apps/web/app/features/stacking/user-positions.tsx
apps/web/app/layouts/nav/nav.tsx
apps/web/app/pages/not-found/not-found.tsx
apps/web/app/pages/stacking/components/independent-stacking-link.tsx
apps/web/app/pages/stacking/components/stacking-provider-table.tsx
apps/web/app/pages/stacking/components/start-earning-button.tsx
apps/web/app/pages/stacking/stacking.tsx
apps/web/app/routes.ts
apps/web/app/routes/stacking/stacking.page.tsx
apps/web/app/store/addresses.ts
apps/web/tests/stacking.spec.ts
packages/ui/src/components/sheet/sheet.web.tsx

If we connect and detect no stacks keys, abort sign in and present warning dialog with link to extension for them to add stacks keys.
https://github.com/user-attachments/assets/6c8a40b7-c662-4a45-8c7c-da930103c27c
I don't have ledger detected in video, but if I did follow instructions, it'd be a relatively easy flow to add stacks keys

refactor(web): add independent stacking msg

---

apps/mobile/ios/Podfile.lock
packages/services/src/assets/sip10-asset.service.ts
packages/services/src/assets/sip9-asset.service.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.client.ts
packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/api/leather/leather-api.error.ts

This PR ensures that we don't continue attempting to refetch SIP10 & SIP09 token metadata that is malformed (422) or missing (404) by returning null in these cases and caching the response.
The cache time for the metadata requests will still invalidate eventually (set interval is ~1 month) giving missing token metadata a chance to update if the status corrects in the future.

feat: prevent missing metadata refetch

---

apps/mobile/src/components/page/page.layout.tsx
apps/mobile/src/services/mobile-http-cache.service.ts
packages/services/src/assets/sip9-asset.service.ts
packages/services/src/collectibles/collectibles.service.spec.ts
packages/services/src/collectibles/collectibles.service.ts
packages/services/src/index.ts
packages/services/src/infrastructure/api/best-in-slot/best-in-slot-api.client.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.client.ts
packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/cache/http-cache.config.ts
packages/services/src/infrastructure/cache/http-cache.service.ts
packages/utils/src/time.ts

This PR addresses both HTTP caching and the protection of HTTP cache keys in the `mobile` pull-to-refresh feature.
HTTP cache configuration has been extracted to a single file (similar to the `workers` repo), simplifying & clarifying the surface area of HTTP calls + TTLs in `@leather.io/services`. 
The `HttpCacheService` has also been refactored into an abstract class to support shared logic adding an "http-" prefix to all cache keys and auto-selecting the TTL for any cache key passed to `fetchWithCache`.
The "http-" prefix is then used in the pull-to-refresh feature in `mobile` to protect all HTTP calls from invalidation.
The result is that only expired cache keys will refetch when a user "refreshes" the mobile app. This helps drives down the number of calls made on page load / refresh …

feat: consolidate http cache config, ref LEA-2101

---

apps/mobile/src/queries/stacks/fetch-fn.ts
apps/mobile/src/queries/stacks/use-broadcast-stx-transaction.ts

Adds the partner header onto Stacks Tx broadcast requests made via `@stacks/transaction`.
Addresses the issue with STX sends failing due to hitting Hiro's unauthenticated rate limit.

feat: authenticate tx broadcast requests to hiro, closes LEA-2631

---

apps/web/app/app.tsx
apps/web/app/components/icons/provider-icon.tsx
apps/web/app/components/pool-overview.tsx
apps/web/app/constants/constants.ts
apps/web/app/constants/query-client.ts
apps/web/app/data/data.ts
apps/web/app/features/stacking/direct-stacking-info/components/active-stacking-info.tsx
apps/web/app/features/stacking/direct-stacking-info/components/liquid-stacking-info-grid.tsx
apps/web/app/features/stacking/direct-stacking-info/components/pending-stacking-info.tsx
apps/web/app/features/stacking/direct-stacking-info/liquid-stacking-info.tsx
apps/web/app/features/stacking/hooks/use-pool-info.tsx
apps/web/app/features/stacking/hooks/use-user-positions-fake-loading.ts
apps/web/app/features/stacking/increase-liquid-stacking/utils/increase-liquid-schema.ts
apps/web/app/features/stacking/pooled-stacking-active-info.tsx
apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-info-grid.tsx
apps/web/app/features/stacking/start-liquid-stacking/components/liquid-stacking-confirmation-steps.tsx
apps/web/app/features/stacking/start-liquid-stacking/utils/stacking-liquid-schema.ts
apps/web/app/features/stacking/start-pooled-stacking/components/choose-pooling-amount.tsx
apps/web/app/features/stacking/start-pooled-stacking/components/pooled-stacking-confirmation-steps.tsx
apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx
apps/web/app/features/stacking/start-pooled-stacking/utils/stacking-pool-form-schema.ts
apps/web/app/features/stacking/start-pooled-stacking/utils/stacking-pool-types.ts
apps/web/app/features/stacking/user-positions.tsx
apps/web/app/pages/stacking/components/stacking-provider-table.tsx
apps/web/app/queries/stacking-tracker/pools.ts
apps/web/app/queries/stacking-tracker/protocols.ts
apps/web/app/utils/fake-loading.ts
apps/web/app/utils/unit-convert.spec.ts
apps/web/app/utils/unit-convert.ts
apps/web/workers/csp.ts

This pr adds 
- request from stacking-tracker for pools specific data
- removes stacking pools hardcoded data on stacking page table (aprs, fees, tvl etc.)

feat(web): remove stacking pools related hardcoded data

---

.github/actions/eas-deploy-android/action.yml
.github/actions/eas-deploy-ios/action.yml
apps/mobile/.eas/workflows/android-maestro-test.yml
apps/mobile/.eas/workflows/ios-maestro-test.yml
apps/mobile/eas.json
packages/ui/package.json

We are getting charged a lot for running these builds. I am exploring using `eas update` so that we don't have to run builds so frequently - but for now I think we should disable all these `dev` builds. This will save us a fair amount of resources used.

CI: reduce number of builds

---

apps/mobile/src/features/account/account.tsx
apps/mobile/src/features/receive/screens/select-account.tsx
apps/mobile/src/features/send/send.tsx
apps/mobile/src/hooks/use-account-addresses.ts
apps/mobile/src/store/accounts/accounts.read.ts
apps/mobile/src/store/keychains/stacks/stacks-keychains.read.ts

This PR fixes a bug whereby previously we were still including **hidden** accounts in our balance and activity calculations. 
I made these changes:
- filter `hidden` accounts out of `stacksSigners` and `derivedAddresses`
- default `useAccounts()` to use `active`, opt in for `hidden`
- **WHEN** users follow the path `Home` -> `Account` -> `Settings` -> `Hide Account` 
- **THEN** on back send them to `Home` and not the hidden account overview
https://github.com/user-attachments/assets/c7b11f9e-792b-48d7-a335-eab2fb4100bf
**Home with all accounts hidden**
https://github.com/user-attachments/assets/d2d6b2d3-c40e-4c2f-a12f-851fc176ba82

fix: LEA-2623: exclude hidden accounts from activity and balances

---

apps/mobile/src/features/qr-scanner/qr-scanner-camera.tsx
apps/mobile/src/features/qr-scanner/qr-scanner-frame.tsx
apps/mobile/src/features/qr-scanner/qr-scanner.tsx

This fixes few QR scanner regressions introduced by expo-camera update:
1. Fix reticle alignment: [ENG-81: Fix QR frame alignment](https://linear.app/leather-io/issue/ENG-81/fix-qr-frame-alignment)
2. Fix entry transition
3. Adjust error timing
4. Add reticle fill animation when changing state.

Fix QR scanner reticle positioning and few more issues, closes ENG-81

---

packages/services/src/infrastructure/api/leather/leather-api.client.ts
packages/services/src/infrastructure/rate-limiter/leather-rate-limiter.ts
packages/services/src/infrastructure/rate-limiter/rate-limiter.service.ts

Implements a priority queue to enforce client-side concurrency limits on Leather API requests.
This PR is necessary to prevent an overload of simultaneous requests as users add a high number of wallet accounts to their device and ensures consistent resource usage during high-volume actions like initial load / refresh.
Max concurrency is currently set at 20 RPS, which favors performance and responsiveness while still maintaining a controlled request flow. This design enables us to support an unbounded number of additional accounts per device w/o hitting rate limits.

feat: add leather api requests to queue

---

apps/web/app/components/icons/bitcoin-icon.tsx
apps/web/app/components/icons/listx-icon.tsx
apps/web/app/components/icons/stacks-icon.tsx
apps/web/app/components/icons/ststx-icon.tsx
apps/web/app/components/pool-overview.tsx
apps/web/app/components/protocol-overview.tsx
apps/web/app/constants/constants.ts
apps/web/app/features/stacking/direct-stacking-info/liquid-stacking-info.tsx
apps/web/app/features/stacking/hooks/stacking.query.ts
apps/web/app/features/stacking/hooks/use-pool-info.tsx
apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-info-grid.tsx
apps/web/app/features/stacking/start-liquid-stacking/start-liquid-stacking.tsx
apps/web/app/features/stacking/start-liquid-stacking/utils/utils-preset-protocols.ts
apps/web/app/features/stacking/start-pooled-stacking/components/preset-pools.tsx
apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx
apps/web/app/features/stacking/user-positions/user-positions.tsx
apps/web/app/pages/stacking/components/stacking-provider-table.tsx
apps/web/app/queries/balance/nft-holdings.ts
apps/web/app/queries/create-get-allowance-contract-callers-query-options.ts
apps/web/app/queries/protocols/dao/balance.ts
apps/web/app/queries/protocols/dao/fee.ts
apps/web/app/queries/protocols/lisa/balance.ts
apps/web/app/queries/protocols/protocol-types.ts
apps/web/app/queries/protocols/use-protocol-balance.ts
apps/web/app/queries/protocols/use-protocol-fee.ts
apps/web/app/queries/protocols/use-protocol-info.tsx

This pr adds:
- real data in liquid stacking protocol overview
- real data on active liquid stacking page
- real market data in all the flows 
- fix part of contract calls queries (use stacks client methods to avoid 429 errs)

feat(web): add liquid stacking protocol overview

---

apps/mobile/metro.config.cjs
apps/mobile/src/app/_layout.tsx
apps/mobile/src/utils/analytics.ts
package.json
packages/analytics/src/events.ts
pnpm-lock.yaml

This PR:
- [adds 'application_first_opened' analytic, ref ENG-88](https://github.com/leather-io/mono/pull/1237/commits/ec084ff09eccf3c5bea8f30658b5c40073f027be)
- [reverses some changes](https://github.com/leather-io/mono/pull/1237/commits/9ee747303363417fece6911691923edbbc731b2b) we needed to enable `FlashList` pre `expo` 53

chore(mobile): add event a sentry event for app opened - ENG-88

---

apps/mobile/metro.config.cjs
package.json
pnpm-lock.yaml

I did some `cleanup` of `FlashList` code yesterday but didn't re-build properly and alas, broke the mobile build. 
This PR re-adds those workarounds to stop us crashing with these errors about `hermes`:

fix(mobile): re-add FlashList resolutions to not crash the build

---

apps/mobile/src/features/send/components/recipient/recipient-guard-sheet.tsx
apps/mobile/src/features/send/components/recipient/use-recipient-state.ts

Fixes a regression with Recipient guard sheet being a frame behind React setting the evaluation severity, and not opening as a result.
**Before:**
https://github.com/user-attachments/assets/076e0d82-6ac6-45d2-a5f4-86c5e5f78a32
**After**
https://github.com/user-attachments/assets/1918b1ab-427b-475e-8e76-88eaa08c30d5

fix(mobile): auto-show guard sheet on severity change, closes ENG-91

---

apps/mobile/src/features/feature-flags/index.ts
apps/mobile/src/queries/balance/runes-balance.query.ts
apps/mobile/src/queries/collectibles/account-collectibles.query.ts

Rune balances are still being incorporated into total and account total balance. 
This PR puts the inclusion of runes balances into totals behind the runes feature flag.

chore(mobile): gate runes total balances behind feature flag

---

apps/mobile/src/features/send/hooks/use-send-max.ts
apps/mobile/src/hooks/use-previous.ts

Fixes a bug with stale max spendable amount when changing/adding a recipient in the Send form. The Max amount will now update accordingly if the recipient, and therefore the fee is updated.
https://github.com/user-attachments/assets/fbc9b6b2-c83f-49b0-bfec-c34d5f4e3fc2

fix(mobile): update max amount in Send form on recipient change, closes ENG-95

---

apps/mobile/src/features/browser/browser/browser-sheet.tsx
apps/web/app/features/stacking/increase-liquid-stacking/utils/utils-increase-liquid-stacking.ts
apps/web/app/features/stacking/start-liquid-stacking/utils/utils-liquid-stacking-stx.ts
apps/web/app/features/stacking/start-pooled-stacking/utils/utils-delegate-stx.ts
apps/web/app/queries/balance/account-balance.hooks.ts
packages/analytics/src/events.ts
packages/utils/src/math/index.ts
packages/utils/src/math/scale-value.spec.ts
packages/utils/src/math/scale-value.ts

We would like telemetry on the volume of use for our stacking providers. This PR adds some telemetry about which pools are used and how much people are stacking. There is very little PII here so I think this is safe to do and this is all public blockchain data.

feat: add stacking tracking

---

apps/web/app/data/data.ts
apps/web/app/features/stacking/hooks/use-pool-info.tsx
apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-info-grid.tsx
apps/web/app/features/stacking/start-pooled-stacking/components/choose-rewards-address.tsx
apps/web/app/features/stacking/start-pooled-stacking/components/pool-reward-protocol-info-reward-token.schema.ts
apps/web/app/features/stacking/start-pooled-stacking/components/preset-pools.tsx
apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx
apps/web/app/pages/stacking/components/stacking-provider-table.tsx

This pr 
- removes btc rewards address input on pools with stx rewards
- enables horizontal scroll on stacking pools tables

fix(web): remove btc rewards address if unnecessary

---

apps/mobile/src/features/browser/browser/browser-sheet.tsx
packages/ui/package.json
packages/ui/src/components/sheet/sheet.native.tsx

Closes LEA-2492
@pete-watters / @edgarkhanzadian biggest change here is to use the bottom sheet container for the browser sheet, which required adding `flex: 1`. I did notice that no other sheets set this to `true` (see image) so it's a safe change but we may want to rething how we handle the container, perhaps just an exported component that can be composed in?

fix: ensure we set proper border radius and use container on browser

---

apps/mobile/src/features/feature-flags/index.ts
apps/mobile/src/features/send/components/recipient/ios-recipient-paste-button.tsx
apps/mobile/src/features/send/components/recipient/recipient-selector/recipient-selector.tsx

Adds a Paste button next to the recipient input in **Send**. The feature is iOS only–Android already comes with a great pasting UI out of the box.
https://github.com/user-attachments/assets/74bdce42-a3a5-4070-b7f4-44de1d5ccc73

feat(mobile): add paste button to recipient selector in Send, closes PRO-80

---

apps/mobile/src/components/balance/balance.tsx
packages/utils/src/money/calculate-money.spec.ts
packages/utils/src/money/format-money.ts

This PR reverts the changes to `formatMoney` from this issue:
https://linear.app/leather-io/issue/LEA-2629/sbtc-activity-amount-showing-scientific-notation
I just wanted to add a passing test to expose where the extension broke.
cc @kyranjamie on changes that were made to `formatMoney`

fix: revert change to format money

---

packages/analytics/src/client.ts

Event properties on mobile were broken because of the spread operator. They were coming through formatted as:
```json
{"0": {"network": "mainnet"}, "platform": "mobile"}
```
but should have been
```json
{"network": "mainnet", "platform": "mobile"}
```

fix: spreading was indexing on 0

---

apps/mobile/src/app/_layout.tsx
apps/mobile/src/components/action-bar/use-action-bar.ts
apps/mobile/src/core/sheet-navigation-container.tsx
apps/mobile/src/features/psbt-signer/psbt-signer.tsx
apps/mobile/src/features/receive/components/receive-asset-item.tsx
apps/mobile/src/features/receive/receive-sheet.tsx
apps/mobile/src/features/receive/receive.tsx
apps/mobile/src/features/receive/screens/asset-details.tsx
apps/mobile/src/features/receive/screens/select-asset.tsx
apps/mobile/src/features/send/components/amount-field.tsx
apps/mobile/src/features/send/components/numpad.tsx
apps/mobile/src/features/send/components/recipient/recipient-selector/recipient-selector-item.tsx
apps/mobile/src/features/send/components/recipient/recipient-selector/recipient-selector.tsx
apps/mobile/src/features/send/components/recipient/recipient-toggle.tsx
apps/mobile/src/features/send/components/recipient/recipient.tsx
apps/mobile/src/features/send/forms/btc/use-btc-form.ts
apps/mobile/src/features/send/forms/stx/use-stx-form.ts
apps/mobile/src/features/send/screens/form.tsx
apps/mobile/src/features/send/screens/select-account.tsx
apps/mobile/src/features/send/screens/select-asset.tsx
apps/mobile/src/features/send/send-sheet.tsx
apps/mobile/src/features/send/send.tsx
apps/mobile/src/features/stacks-tx-signer/stacks-tx-signer.tsx
apps/mobile/src/utils/analytics.ts
eslint.config.js
packages/analytics/src/events.ts

PR Adds few small improvements to the telemetry Setup and event tracking for Send & Receive
**No `void`**
Disabled `no-floating-promises` just for this method, as **all** usages of it are fire & forget. I've debated adding a separate `trackAsync` method, but since we basically never wait for the promise resolution, silencing the rule is safe and the least noisy solution.
**No optional chaining**
`analytics` client now uses a proxy to ignore calls and can be safely called as `analytics.track`. I intentionally didn't update usage sites to keep the PR small.
**Disable Sentry in development mode**
Noticed few exceptions in Sentry from local setups. Sneaking in a commit to fix that.
* Fixed `SheetNavigator` tracks not being called due to a missing ref. 
* Added a `base` prefix to …

Add analytics to Send & Receive + setup improvements

---

packages/services/src/activity/activity.service.ts
packages/services/src/activity/stacks-asset-transfer.utils.spec.ts
packages/services/src/activity/stacks-asset-transfer.utils.ts
packages/services/src/activity/stacks-tx-activity.utils.spec.ts
packages/services/src/activity/stacks-tx-activity.utils.ts
packages/services/src/assets/stacks-asset.utils.ts
packages/services/src/balances/sip10-balances.service.spec.ts
packages/services/src/balances/sip10-balances.service.ts
packages/services/src/balances/stx-balances.service.spec.ts
packages/services/src/balances/stx-balances.service.ts
packages/services/src/infrastructure/api/hiro/hiro-multi-page.spec.ts
packages/services/src/infrastructure/api/hiro/hiro-multi-page.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.client.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.types.ts
packages/services/src/infrastructure/api/hiro/hiro-stacks-api.utils.ts
packages/services/src/infrastructure/cache/http-cache.config.ts

Updates the Stacks API client and consuming services in `@leather.io/services` to use the new V2 balance endpoints, [per Hiro's request](https://trustmachines.slack.com/archives/C05T570TNQJ/p1742315714930689).

refactor: migrate to new hiro balance endpoints in services package, closes LEA-2420

---

apps/web/app/components/post-info-hover-icon.tsx
apps/web/app/utils/post-link.test.ts
apps/web/app/utils/post-link.ts
apps/web/vitest.config.js

Info icon URLs are currently still broken in prod/live as the previous fix only targeted local env. URLs are now being checked beforehand so the fix works in dev & prod

fix: check info url before environment

---

apps/web/app/store/addresses.ts
apps/web/package.json
pnpm-lock.yaml

Integrates internal quests API to complete Zealy "connect earn" task when users connect to web app.
This was originally added only to the legacy `earn.leather.io`.

feat(web): complete zealy quest on wallet connect
