leather-io/mono

packages/tokens/src/semantic-tokens.ts
Ref [#4805](https://github.com/leather-wallet/extension/issues/4805)
=> fix: component bg hover color, ref #4805

package-lock.json, packages/tsconfig-config/tsconfig.base.json, packages/types/package.json, packages/types/src/index.ts, packages/types/src/methods/get-addresses.ts, packages/types/src/methods/get-info.ts, packages/types/src/methods/send-transfer.ts, packages/types/src/methods/sign-message.ts, packages/types/src/methods/sign-psbt.ts, packages/types/src/rpc/index.ts, packages/types/src/utils.ts, packages/types/tsconfig.json
Copied the types package from btckit to our own npm scope
=> feat(types): add types package

packages/types/README.md, packages/types/package.json, packages/types/src/index.ts, packages/types/src/methods/get-addresses.ts, packages/types/src/methods/sign-message.ts
=> fix(types): missing readme, files

packages/tokens/src/semantic-tokens.ts
=> fix: component bg hover color

apps/mobile/metro.config.js
FIx metro config resolving tsconfig paths + some prettier on the file
=> fix: metro config tsconfig paths resolution

packages/tokens/package.json, packages/tokens/src/colors.ts, packages/tokens/src/index.ts, packages/tokens/src/tokens.ts
Fixes/updates some changes needed to remove current hardcoded values in the extension.
=> fix: token border colors

packages/types/src/index.ts, packages/types/src/methods/stx-sign-message.ts
Related to https://github.com/leather-wallet/extension/issues/4945
Adds previously untyped msg
=> chore: add stx message signing types

packages/tokens/src/colors.ts
=> fix: Tone down background-primary in dark mode

packages/tokens/package.json
I forgot to bump the package version on this PR https://github.com/leather-wallet/mono/pull/85.
I'm going to manually publish and will investigate automating this better
=> chore: update package version

packages/crypto/package.json
=> fix: missing pnpm prefix

packages/query/src/stacks/bns/bns.utils.ts
Unit test is failing when installed in the extension.
=> fix: stacks queries unit test failing

.dependency-cruiser.cjs
closes https://github.com/leather-wallet/issues/issues/82
=> feat: prevent react import in models

packages/query/index.ts, packages/query/src/stacks/transactions/raw-transaction-by-id.hooks.ts
I keep forgetting I need to add new files to the export list ...and moving a hook here with others. Release-please didn't include this in last auto PR, so need a fresh merge to fix.
=> fix: export query changes

packages/query/src/query-prefixes.ts
Test to try and fix release-please not auto generating the release PR. Docs say to rerun the workflow, but that didn't work for me.
=> fix: query release

packages/query/index.ts, packages/query/src/bitcoin/address/transactions-by-address.query.ts, packages/query/src/bitcoin/address/utxos-by-address.hooks.ts, packages/query/src/bitcoin/address/utxos-by-address.query.ts, packages/query/src/bitcoin/clients/best-in-slot.ts, packages/query/src/bitcoin/clients/bitcoin-client.ts, packages/query/src/bitcoin/fees/fee-estimates.query.ts, packages/query/src/bitcoin/ordinals/brc20/brc20-tokens.query.ts, packages/query/src/bitcoin/ordinals/inscription.utils.ts, packages/query/src/bitcoin/ordinals/inscriptions.query.ts, packages/query/src/bitcoin/runes/runes-outputs-by-address.query.ts, packages/query/src/bitcoin/runes/runes-ticker-info.query.ts, packages/query/src/bitcoin/runes/runes-wallet-balances.query.ts, packages/query/src/bitcoin/runes/runes.utils.ts, packages/query/src/bitcoin/transaction/transaction.query.ts, packages/query/src/bitcoin/transaction/use-bitcoin-broadcast-transaction.ts, packages/query/src/bitcoin/transaction/use-check-utxos.ts, packages/query/types/inscription.ts
Inscription by address query  is used for filtering native segwit utxos.
This pr changes the the source of data to bis api, other queries will be refactored later
=> feat: implement bis api for inscription by address query

packages/query/src/bitcoin/clients/best-in-slot.ts, packages/query/src/bitcoin/clients/bitcoin-client.ts, packages/query/src/bitcoin/ordinals/inscription-text-content.query.ts, packages/query/src/bitcoin/ordinals/inscription.utils.ts, packages/query/src/bitcoin/ordinals/inscriptions-infinite.query.ts, packages/query/src/bitcoin/ordinals/inscriptions.hooks.ts, packages/query/src/bitcoin/runes/runes-outputs-by-address.query.ts, packages/query/src/bitcoin/runes/runes-ticker-info.query.ts, packages/query/src/bitcoin/runes/runes-wallet-balances.query.ts, packages/query/src/rate-limiter/best-in-slot-limiter.ts, packages/query/src/stacks/stacks-client.ts
This pr refactors  inscriptions infinite query to use BiS api
=> refactor: inscriptions infinite query to use bis api

packages/crypto/src/index.ts
=> fix: crypto pkg release

packages/rpc/src/methods/get-addresses.ts
Companion PR to https://github.com/leather-io/extension/pull/5698
Thx @sjc5
=> fix(rpc): add stx public key

apps/mobile/README.md, apps/mobile/src/app/wallet/(tabs)/_layout.tsx, apps/mobile/src/app/wallet/(tabs)/action-bar.tsx, apps/mobile/src/app/wallet/(tabs)/all-assets.tsx, apps/mobile/src/assets/plus-icon.svg, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po
This PR makes the Action Bar dynamic so that if no wallets have been created it shows `Add Wallet` and links to `APP_ROUTES.WalletCreateNewWallet`
=> feat: link to `Add Wallet` if no wallets created

apps/mobile/src/app/_layout.tsx, apps/mobile/src/state/settings/settings.slice.ts, apps/mobile/src/utils/when-theme.ts
Before
After
https://github.com/user-attachments/assets/de81565c-2223-4cfb-848c-8e9bb95f2f4a
=> fix(mobile): status bar colour

packages/models/src/network/network.model.ts
This pr adds hiro "/extended" mainnet and testnet urls
=> feat: add hiro extended url

packages/ui/package.json, packages/ui/tsconfig.web.json, packages/ui/tsup.config.web.ts, pnpm-lock.yaml
Hoping this fixes the web ui build, going to use the same plugin as I did for the native build which seems to work, maybe the clean plugin ended up removing the src files? I'm not sure why it was working for me locally.
cc @pete-watters
=> fix: web ui build missing src folder

packages/constants/src/index.ts
This PR adds the support link to constants
=> fix: update support links, ref leather-io/extension#5813

.gitignore, packages/ui/package.json, packages/ui/src/components/skeleton-loader/skeleton-loader.native.stories.tsx, packages/ui/src/components/skeleton-loader/skeleton-loader.native.tsx, pnpm-lock.yaml
This PR is a clone of [this one](https://github.com/leather-io/mono/pull/411) from an external contributor. 
Thanks @adrianocola 👏
=> feat: add native Skeleton Loader to UI library

apps/mobile/src/app/wallet/settings/networks/index.tsx, apps/mobile/src/app/wallet/settings/networks/networks-screen.layout.tsx, apps/mobile/src/app/wallet/settings/networks/networks-switcher.tsx, apps/mobile/src/features/settings/theme-sheet/theme-sheet.layout.tsx, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po, apps/mobile/src/store/settings/settings.write.ts
This PR is branched off my theme settings branch. It wires up being able to change networks.
=> feat: settings network

apps/mobile/ios/Podfile.lock, apps/mobile/src/app/wallet/_layout.tsx, apps/mobile/src/app/wallet/wallet-settings/configure/[wallet]/[account]/choose-avatar.tsx, apps/mobile/src/app/wallet/wallet-settings/configure/[wallet]/[account]/index.tsx, apps/mobile/src/components/avatar-icon.tsx, apps/mobile/src/features/settings/choose-avatar/avatar-button.tsx, apps/mobile/src/features/settings/choose-avatar/avatars.tsx, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po, apps/mobile/src/routes.ts, apps/mobile/src/store/accounts/accounts.write.ts
https://github.com/user-attachments/assets/ad8b261e-6ca6-480d-ae23-46261ab9c56c
=> feat: add avatar selector

apps/mobile/src/app/wallet/create-new-wallet.tsx, apps/mobile/src/app/wallet/wallet-settings/configure/[wallet]/view-secret-key.tsx, apps/mobile/src/components/create-new-wallet/mnemonic-display.tsx, apps/mobile/src/components/create-new-wallet/mnemonic-word-box.tsx, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po, apps/mobile/src/store/storage-persistors.ts, packages/ui/src/icons/index.native.ts, packages/ui/src/icons/key-icon.native.tsx
https://github.com/user-attachments/assets/ca8af526-9df8-4456-88fa-9742bf3dc439
=> fix: update mnemonic key view

apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po
I made a mistake of some kind when rebasing https://github.com/leather-io/mono/pull/421/ and it introduced some translation errors which I have now fixed. 
It added a lot of `<<<<<<< HEAD` comments into the file
=> fix: fix issue with translations leather-io/issues#136

README.md, docs/core/ARCHITECTURE.md
Just a few small changes to get my feet wet in the repository and make it clear to chumps like me how to get the environment ready to run.
=> chore: update readme documentation

apps/mobile/src/app/wallet/create-new-wallet.tsx, apps/mobile/src/app/wallet/wallet-settings/configure/[wallet]/view-secret-key.tsx, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po
This PR updates some copy for the view secret key screens [as per ](https://github.com/leather-io/issues/issues/318)
=> fix: update secret key copy, ref leather-io/issues#318

apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po, apps/mobile/src/store/storage-persistors.ts
I can't reproduce in development even if I run the dev branch now. Hoping this fixes testflight, or someone else can test the update path?
To fix:
=> fix: redux persist config

packages/ui/tsup.config.web.ts
Not sure how I missed this working locally, but I wasn't bundling the types
=> fix(ui): types not bundled with package

apps/mobile/src/app/(home)/settings/display/display-cell.tsx, apps/mobile/src/app/(home)/settings/display/index.tsx, apps/mobile/src/components/private-text.tsx, apps/mobile/src/components/widgets/components/balance/fiat-balance.tsx, apps/mobile/src/components/widgets/components/balance/token-balance.tsx, apps/mobile/src/components/widgets/tokens/tokens-widget.tsx, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po, apps/mobile/src/store/settings/settings.read.ts, apps/mobile/src/store/settings/settings.ts, apps/mobile/src/store/settings/settings.write.ts, packages/ui/src/icons/users-two-icon.native.tsx, packages/ui/src/icons/wallet-plus-icon.native.tsx
This PR adds privacy mode to settings so that a user can show or hide their account balances. In addition to toggling the setting itself, a user can also now press on any balance to show/hide all balances...
=> feat: settings privacy mode

packages/ui/src/components/approver/approver-context.shared.ts, packages/ui/src/components/approver/approver.web.tsx, packages/ui/src/components/approver/components/approver-header.web.tsx, packages/ui/src/components/approver/stories/approver-demo.web.tsx, packages/ui/src/components/approver/stories/approver.web.stories.tsx, packages/ui/src/components/flag/flag.web.tsx, packages/ui/src/components/item-layout/item-layout-with-buttons.web.tsx, packages/ui/src/components/item-layout/item-layout.web.stories.tsx, packages/ui/src/components/item-layout/item-layout.web.tsx, packages/ui/src/components/pressable/pressable.web.stories.tsx
Account card component in extension is slightly bigger, explaining height discrepancies
=> fix(ui): approver margin updates

apps/mobile/src/app/(home)/hardware-wallets.tsx, apps/mobile/src/app/(home)/mpc-wallets.tsx, apps/mobile/src/app/(home)/settings/index.tsx, apps/mobile/src/components/add-wallet/add-wallet-sheet.layout.tsx, apps/mobile/src/components/add-wallet/add-wallet-sheet.tsx, apps/mobile/src/components/sheets/notify-user-sheet.layout.tsx, apps/mobile/src/locales/en/messages.po, apps/mobile/src/locales/pseudo-locale/messages.po
This PR wires up the `upcoming features` in settings (Contacts and Fees). It was waiting on the `NotifyUserSheet` from @edgarkhanzadian ...I renamed a few things here for clarity (rather than generic names like `OptionData`).
=> feat: settings upcoming features

packages/models/src/network/network.model.ts, packages/models/src/network/network.schema.ts
Forgot to update the network config id, added helper util
=> fix: issue with testnet4 config

apps/mobile/src/app/(home)/settings/networks/index.tsx, apps/mobile/src/store/keychains/bitcoin/bitcoin-keychains.read.ts, packages/models/src/network/network.model.ts, packages/models/src/network/network.schema.ts, packages/query/src/bitcoin/address/transactions-by-address.query.ts, packages/query/src/bitcoin/address/utxos-by-address.query.ts, packages/query/src/bitcoin/clients/bitcoin-client.ts, packages/query/src/bitcoin/fees/fee-estimates.hooks.ts, packages/query/src/bitcoin/ordinals/inscriptions-infinite.query.ts, packages/query/src/bitcoin/runes/runes-outputs-by-address.query.ts, packages/query/src/bitcoin/runes/runes-wallet-balances.query.ts, packages/query/src/bitcoin/runes/runes.hooks.ts
I went back and forward on the best schema for this, and ended up adding the separate prop, even though it can be inferred.
=> fix(models): testnet4 schema updates

apps/mobile/src/app/(home)/recover-wallet.tsx
Fix vertical alignment of text on Android, closes lea-1582
=> fix: vertical alignment of text set to top

packages/query/src/rate-limiter/hiro-rate-limiter.ts, packages/query/src/stacks/leather-headers.ts, packages/query/src/stacks/stacks-client.ts
This pr increases hiro rpm and fixes lost leather custom request header
=> feat: increase hiro api rpm

apps/mobile/src/app/(home)/create-new-wallet.tsx, packages/ui/src/components/blur-view/blur-view.native.tsx
Adds experimental support for blur view on android. 
Not 100% sure this is the route the the team wants to take but it is a potential short term solution here.
=> fix: add experimental support for blur view on android

.release-please-manifest.json, apps/mobile/src/utils/analytics.ts, packages/analytics/README.md, packages/analytics/src/client.spec.ts, packages/analytics/src/client.ts, packages/analytics/src/events.ts, packages/analytics/src/index.ts, packages/analytics/src/types.ts, packages/analytics/tsconfig.json, pnpm-lock.yaml, release-please-config.json
- Improve the API interface: remove need for consuming package to import any types, improve property type with rest param tuple type so `undefined` is an optional param but events with properties require them.
- Set up CI to deploy @leather.io/analytics
=> Release @leather.io/analytics via release-please

.github/workflows/publish-storybook.yml
Migrating job from extension to mono
=> ci(ui): publish storybook web

packages/models/src/network/network.model.ts
Updates networks and adds a new live testnet instance for sBTC testing
=> feat(models): sbtc testnet network

packages/panda-preset/src/recipes/button-recipe.ts, packages/ui/src/components/button/button.web.stories.tsx, packages/ui/src/components/button/button.web.tsx
https://github.com/user-attachments/assets/b67dcadd-4352-43c2-958a-07db26440aa5
https://github.com/user-attachments/assets/20e66349-dc74-4032-ac76-e6caf235e3ed
=> fix: button spinner color, closes LEA-1773

apps/mobile/src/app/(home)/account/[account]/account-overview-card.tsx, apps/mobile/src/app/(home)/home/home.tsx, apps/mobile/src/components/headers/components/header-options.tsx, apps/mobile/src/components/widgets/accounts/accounts-widget.tsx, apps/mobile/src/components/widgets/accounts/components/cards/create-wallet-card.tsx
5 for one Black Friday PR with a few adjustments for Leatherhood release
https://github.com/user-attachments/assets/0ab884a8-b1dc-4af9-aff1-5b7170ddaf20
=> Leatherhood: Accounts fixes

packages/query/types/remote-config.ts
We don't know all the contracts yet, and this'll allow us to update with a release
=> fix: add sbtc config to wallet config

apps/mobile/src/app/(home)/settings/display/index.tsx
Temporarily hardcoding the haptics setting text which is not working in Testflight
=> fix: hardcode haptics text temporarily, ref LEA-1780

apps/mobile/src/app/(home)/settings/index.tsx, apps/mobile/src/common/display-preference.ts, apps/mobile/src/features/settings/account-identifier-sheet.tsx
- stx is layer 2 instead of layer 1
- display preference subtitle
=> fix: localization strings

apps/mobile/maestro/flows/hide-account.yaml, apps/mobile/src/app/(home)/settings/wallet/configure/[wallet]/[account]/index.tsx
This PR makes sure we toggle text and icon when hiding accounts
https://github.com/user-attachments/assets/8590041b-9bfe-49bb-82a3-0a43f3de8500
=> fix: toggle text and icon when hiding account

apps/mobile/maestro/flows/receive.yaml, apps/mobile/src/components/full-height-sheet/full-height-sheet-header.tsx, apps/mobile/src/features/receive/receive-sheets/get-assets.ts, apps/mobile/src/features/receive/receive-sheets/receive-asset-item.tsx, apps/mobile/src/features/receive/receive-sheets/receive-asset-sheet.tsx, apps/mobile/src/features/receive/receive-sheets/select-asset.tsx, apps/mobile/src/shared/test-id.ts
This PR adds a `Receive` page which shows address details 
https://linear.app/leather-io/issue/LEA-1633/receive-page
https://github.com/user-attachments/assets/2d82a764-ecfe-4105-a6cd-efaedee2554b
=> fix: add receive sheet UI, ref LEA-1633

apps/mobile/src/features/send/send-form/loaders/send-form-btc-loader.tsx
bug: 
https://github.com/user-attachments/assets/d545d1b3-0dc5-4773-92d0-a413bc875ed5
fix:
https://github.com/user-attachments/assets/42827010-0bc5-4daf-be14-f919b2ce6ca7
=> fix: wait for utxos to load before creating context [LEA-1900]

apps/mobile/.eas/common/maestro.yml, docs/e2e-tests.md
This PR adds new maestro tests to the Expo CI
=> ci: add new tests to CI, ref LEA-1858

packages/rpc/package.json, packages/rpc/src/methods/stacks/_clarity-values.ts, packages/rpc/src/methods/stacks/_stacks-helpers.ts, packages/rpc/src/methods/stacks/stx-call-contract.ts, packages/rpc/src/methods/stacks/stx-deploy-contract.ts, packages/rpc/src/methods/stacks/stx-transfer-stx.ts, pnpm-lock.yaml
Copy paste fail adding some new types
=> fix(rpc): incorrect contract call schema

apps/mobile/src/app/(home)/settings/display/index.tsx, packages/services/src/balances/sip10-balances.service.spec.ts
This PR enables the haptics setting in production so it will be available to leatherhood users
=> chore: enable haptics setting, ref LEA-2031

apps/mobile/ios/Podfile.lock, apps/mobile/package.json, apps/mobile/src/features/accounts/components/account-address.tsx, apps/mobile/src/hooks/use-account-display-name.ts, apps/mobile/src/store/settings/settings.read.ts, pnpm-lock.yaml
This PR connects BNS names to mobile and allows them to appear in the account card once the account identifier setting is enabled 
https://github.com/user-attachments/assets/7914d438-0536-4b81-857e-d8bbfd17c93d
=> feat: add bns-names to accounts, ref LEA-1826

packages/rpc/src/index.ts, packages/rpc/src/methods/stacks/stx-call-contract.ts
Some type changes I need to fix errors here:
https://github.com/leather-io/extension/pull/6060
=> fix: stx call contract types

packages/rpc/src/methods/stacks/stx-deploy-contract.ts
Needed in the extension for: https://linear.app/leather-io/issue/LEA-1956/sip-30-add-stx-deploycontract-api-on-extension
=> fix: update stx deploy contract types

packages/query/src/common/remote-config/remote-config.query.ts, packages/utils/src/spam-filter/spam-filter.spec.ts, packages/utils/src/spam-filter/spam-filter.ts
This pr adds spam filter whitelist
=> feat: add spam filter whitelist

packages/rpc/src/index.ts
Conventional commits behaviour is super annoying. My last changes were really a refactor, but I still wanted a release, as this is internal tooling.
=> fix: add comment, trigger release

apps/mobile/package.json, package.json, packages/analytics/package.json, packages/bitcoin/package.json, packages/crypto/package.json, packages/provider/package.json, packages/query/package.json, packages/rpc/package.json, packages/services/package.json, packages/stacks/package.json, packages/ui/package.json, packages/ui/src/components/collectibles/web/collectible-text.layout.web.tsx, packages/ui/src/components/collectibles/web/inscription-preview-card/components/inscription-text.layout.web.tsx, packages/ui/src/components/collectibles/web/inscription-text.web.tsx, packages/utils/package.json, pnpm-lock.yaml
This PR fixes various [security alerts](https://github.com/leather-io/mono/security/dependabot) we have in the monorepo
=> chore: mono security updates

apps/mobile/src/store/settings/settings.read.ts
Mobile fix for: https://github.com/leather-io/extension/pull/6133
=> fix: mobile stacks network

packages/query/src/stacks/balance/account-balance.query.ts
Attempted fix for https://github.com/leather-io/extension/issues/5965
=> fix(query): add refetch interval stacks balances

packages/rpc/README.md
Markdown table with supported SIP-30 endpoints
=> chore(rpc): sip30 support table

packages/rpc/src/methods/get-addresses.spec.ts, packages/rpc/src/methods/get-addresses.ts, packages/rpc/src/methods/stacks/stx-get-addresses.ts
Updates `getAddress` and `stx_getAddresses` schemas to support networks
=> fix(rpc): getAddress network support, ref LEA-2195

packages/ui/src/exports.web.ts, packages/ui/src/utils/use-clipboard.web.ts
adds [copy to clipboard hook](https://github.com/leather-io/extension/blob/dev/src/app/common/hooks/use-copy-to-clipboard.ts) from extension, we will need this in web app as well
=> feat: add use clipboard

packages/rpc/src/index.ts, packages/rpc/src/rpc/helpers.spec.ts, packages/rpc/src/rpc/helpers.ts, packages/rpc/src/rpc/schemas.ts
Using this to pass events in extension
=> feat(rpc): helper encoding util

packages/rpc/src/rpc/helpers.ts
=> fix(rpc): actually export encode fns

apps/mobile/src/features/send/send-form/hooks/use-send-form-btc.tsx, apps/mobile/src/features/send/send-form/hooks/use-send-form-stx.tsx, apps/mobile/src/features/send/send-form/validation/btc.validation.ts, apps/mobile/src/features/send/send-form/validation/stx.validation.ts, apps/mobile/src/features/stacks-tx-signer/stacks-tx-signer.tsx, eslint.config.js, packages/models/src/transactions/transaction-error.model.ts, packages/stacks/src/validation/amount-validation.spec.ts, packages/stacks/src/validation/amount-validation.ts, packages/stacks/src/validation/stacks-error.ts, packages/stacks/src/validation/transaction-validation.spec.ts, packages/stacks/src/validation/transaction-validation.ts
This PR adds validation checks for Stacks transactions and also analytic events on errors which match the extension behaviour 
https://github.com/user-attachments/assets/ed8e8118-a093-4a92-b278-b7ac2c3a492a
=> feat: stacks transaction validation, ref LEA-1681

.github/workflows/pr-guard.yml
See PR description from extension https://github.com/leather-io/extension/pull/6169
=> ci: pr label guards

packages/query/src/common/remote-config/remote-config.query.ts
This pr adds config fallback in case of error 
this fixes stx send page fee errors
=> feat: add fallback if config fetch failed, LEA-1806

package.json, packages/query/package.json, packages/services/package.json, pnpm-lock.yaml
update axios lib due to [vulnerability issue](https://security.snyk.io/package/npm/axios)
audit fail in extension:  https://github.com/leather-io/extension/actions/runs/13787293935/job/38558213209?pr=6177
=> chore: update axios lib

packages/utils/src/spam-filter/spam-filter.spec.ts
=> feat: spam filter test

apps/mobile/ios/Podfile.lock
Fixes `Podfile.lock` conflicts introduced on commit https://github.com/leather-io/mono/commit/fc8364bcfb90e582043df52e8adf7111343fc7db.
[Slack discussion.](https://trustmachines.slack.com/archives/C05LAP952E7/p1741701758320129)
=> fix: podfile.lock conflicts

.github/workflows/check-signed-commits.yml
Same as on extension, adds check for signed commits
=> ci: check signed commits

apps/web/app/components/dummy.tsx, apps/web/app/components/page.tsx, apps/web/app/components/table.tsx, apps/web/app/features/sign-in-button/sign-in-button.layout.tsx, apps/web/app/layouts/footer/footer.layout.tsx, apps/web/app/layouts/nav/nav.tsx, apps/web/app/pages/earn/components/earn-instructions.tsx, apps/web/app/pages/earn/components/earn-provider-table.tsx, apps/web/app/pages/earn/earn.tsx, apps/web/app/pages/home/home.tsx, apps/web/package.json, package.json, packages/panda-preset/src/borders.ts, packages/panda-preset/src/tokens.ts, packages/ui/src/components/collectibles/web/collectible-item.layout.web.tsx, pnpm-lock.yaml
This PR adds some UI for the earn homepage, and the beginnings of the table component.
This PR is really just incremental progress, and isn't entirely complete, but I'm eager to get it in to avoid clashes with @alter-eggo's work.
=> feat(web): earn page

packages/constants/src/index.ts
Updates leather api url constant.
=> refactor: update leather api url

.github/workflows/release-please.yml
Only publish packages, not apps
=> ci: publish only packages

apps/web/app/features/stacking/hooks/stacking.query.ts, apps/web/app/features/stacking/providers/stacking-client-provider.tsx, apps/web/app/features/stacking/utils/types-preset-pools.ts, apps/web/app/helpers/utils.ts, apps/web/app/pages/stacking/components/earn-provider-table.tsx, apps/web/app/root.tsx, apps/web/app/routes.ts, apps/web/app/routes/stacking/index.tsx, apps/web/app/routes/stacking/stacking.tsx, apps/web/app/store/addresses.ts, apps/web/package.json, apps/web/vite.config.ts, packages/query/index.ts, pnpm-lock.yaml
This pr adds
- stacking route
- query hooks
- polyfill required packages
=> feat: add stack in a pool page

apps/mobile/src/app/(home)/activity/components/activity-widget.tsx, apps/mobile/src/app/(home)/settings/display/index.tsx, apps/mobile/src/features/browser/approver-sheet/get-addresses/get-addresses.layout.tsx
Lingui was failing to compile as we had:
- some duplicate keys
- an error with a dynamic key for theme
We need to get this merged to try and auto sync these keys to crowdin for an internal relase
=> fix: fix lingui

.github/workflows/release-please.yml, .github/workflows/sign-release-commit.yml
Take 2. Job that watches for `release-please-**` PRs and rebases the commit with signature. Untested, need to push test PR when merged to verfiy.
=> ci: run --gpg-sign on release prs

apps/mobile/eas.json, apps/mobile/src/app/activity/activity.layout.tsx, apps/mobile/src/app/settings/wallet/configure/[wallet]/[account]/choose-avatar.tsx, apps/mobile/src/components/create-new-wallet/mnemonic-display.tsx, apps/mobile/src/features/send/error-messages.ts, apps/mobile/src/features/waitlist/ids.ts
This PR bundles together a few fixes and improvements:
- adjusts padding on icon page [LEA-2003](https://linear.app/leather-io/issue/LEA-2003)
- adds waitlist trigger for `Save to` [LEA-1825](https://linear.app/leather-io/issue/LEA-1825) 
- fixes bug with lingui key
- manually specifies latest iOS version in `eas.json` to appease app store
**Icon padding**
**Save to waitlist**
https://github.com/user-attachments/assets/f4059fb7-1b33-43bd-9741-4547fda01b84
**eas.json issue**
=> fix: miscellaneous clean up tasks

apps/mobile/src/queries/transaction/use-check-utxos.ts, packages/query/src/bitcoin/ordinals/inscriptions.query.ts
I believe the path was just incorrect here bc the comments and naming of functions indicated we were using `ordinals.com`. I have tested this locally in the extension, and it appears to fix the long delay when sending a bitcoin tx.
=> fix: utxo inscription check html page path

packages/ui/src/components/pressable/pressable.utils.native.ts
Removes a significant rendering bottleneck caused by press effects implementation that came into light when I attempted rendering large amount of (virtualized) pressables into a sheet. 
Skipping a screencast–I wasn't able to capture a meaningful difference on a video, even though it was very noticeable otherwise.
=> fix(ui): improve Pressable performance

apps/web/app/app.tsx, apps/web/app/components/error-label.tsx, apps/web/app/features/error/error-layout.tsx, apps/web/app/features/page/error.tsx, apps/web/app/features/stacking/components/address.tsx, apps/web/app/features/stacking/components/choose-pooling-amount.tsx, apps/web/app/features/stacking/components/choose-pooling-conditions.tsx, apps/web/app/features/stacking/components/choose-rewards-address.tsx, apps/web/app/features/stacking/components/pooling-details.tsx, apps/web/app/features/stacking/start-pooled-stacking.tsx, apps/web/app/features/stacking/utils/stacking-pool-form-schema.ts, apps/web/app/features/stacking/utils/types.ts, apps/web/app/features/stacking/utils/utils-preset-pools.ts, apps/web/app/queries/stacks/use-stacks-pending-transactions.ts, apps/web/app/queries/transaction/use-transactions-with-transfers.query.ts, apps/web/app/root.tsx, apps/web/app/routes/stacking/stacking.tsx, apps/web/app/utils/external-links.ts, apps/web/package.json, apps/web/vite.config.ts, eslint.config.js, pnpm-lock.yaml
This pr 
- adds details section in stack in a pool form (will fix ui in the next pr)
- err page (we will need design for this)
current  state of form page
=> feat: stack in a pool form, part 2

apps/web/app/features/stacking/components/choose-pooling-amount.tsx, apps/web/app/features/stacking/components/choose-rewards-address.tsx, apps/web/app/features/stacking/components/stacking-layout.tsx, apps/web/app/features/stacking/components/stacking-steps-card.tsx, apps/web/app/features/stacking/start-pooled-stacking.tsx
This pr adds stacking submit form card and fixes btc input form validation
Will add amount validation and submit logic (1st part) in sep pr
Will fix ui then 
https://github.com/user-attachments/assets/a5cb3576-40f6-4e06-8454-901236af4f59
=> feat: stack in a pool form, part 3

packages/analytics/src/events.ts
Minor update needed for the extension to track legacy tx signing events.
=> fix: tx request analytics event

apps/web/.gitignore, apps/web/app/features/stacking/start-liquid-stacking.tsx, apps/web/app/features/stacking/utils/stacking-liquid-schema.ts, apps/web/app/features/stacking/utils/types-preset-protocols.ts, apps/web/app/pages/stacking/components/earn-provider-table.tsx, apps/web/app/pages/stacking/liquid-stacking.tsx, apps/web/app/pages/stacking/pooled-stacking.tsx, apps/web/app/routes.ts, apps/web/app/routes/stacking/liquid-stacking.tsx, apps/web/app/routes/stacking/pooled-stacking.tsx
This pr adds liquid stacking routes, basic components, necessary data, etc
https://github.com/user-attachments/assets/6646ac7b-4c2d-40a5-b90c-c32dadc13801
=> feat: liquid stacking form, part 1

apps/web/app/features/stacking/components/choose-pooling-amount.tsx, apps/web/app/features/stacking/components/preset-pools.tsx, apps/web/app/features/stacking/components/stacking-info-grid.layout.tsx, apps/web/app/features/stacking/components/stacking-info-grid.tsx, apps/web/app/features/stacking/pooled-stacking-active-info.tsx, apps/web/app/features/stacking/start-liquid-stacking.tsx, apps/web/app/features/stacking/start-pooled-stacking.tsx, apps/web/app/features/stacking/utils/stacking-pool-form-schema.ts, apps/web/app/pages/stacking/components/earn-provider-table.tsx, apps/web/app/pages/stacking/pooled-stacking-active.tsx, apps/web/app/pages/stacking/pooled-stacking.tsx, apps/web/app/routes.ts, apps/web/app/routes/stacking/liquid-stacking.tsx, apps/web/app/routes/stacking/pooled-stacking-active.tsx
This pr adds amount validation and stacked pool state
there is wrong redirect route in the video... fixed in the pr
https://github.com/user-attachments/assets/c9a92787-edf1-4d89-a8c6-ef42b2bb0efc
=> feat: add stack in a pool form, part 5

apps/web/app/components/confirmations/confirmation-steps.tsx, apps/web/app/components/explainer.tsx, apps/web/app/features/stacking/components/address.tsx, apps/web/app/features/stacking/components/stacking-conditions.tsx, apps/web/app/features/stacking/components/stacking-contract-details.tsx, apps/web/app/features/stacking/components/stacking-form-steps-panel.tsx, apps/web/app/features/stacking/components/stacking-layout.tsx, apps/web/app/features/stacking/components/start-stacking-drawer.tsx, apps/web/app/features/stacking/start-liquid-stacking/components/liquid-stacking-confirmation-steps.tsx, apps/web/app/features/stacking/start-liquid-stacking/start-liquid-stacking.tsx, apps/web/app/features/stacking/start-pooled-stacking/components/choose-pooling-duration.tsx, apps/web/app/features/stacking/start-pooled-stacking/components/pooled-stacking-confirmation-steps.tsx, apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx
This pr adds stack in pool form and liquid stack mobile view 
https://github.com/user-attachments/assets/39b191cb-7f7f-42b3-8343-0f94f16b0581
=> feat: stack in pool form, part 6

apps/web/app/features/stacking/start-liquid-stacking/utils/types-preset-protocols.ts, apps/web/app/features/stacking/start-liquid-stacking/utils/utils-liquid-stacking-stx.ts, apps/web/app/pages/stacking/liquid-stacking-active.tsx, apps/web/app/routes.ts, apps/web/app/routes/stacking/liquid-stacking-active.tsx
This pr adds:
- active liquid stacking route (without design yet)
- fixes issue with liquid stacking submission (it was a typo)
- (mobile view of liquid stacking page was added earlier)
video of liquid stacking flow
https://github.com/user-attachments/assets/045078be-0da3-41b1-9b9a-3fee95c38163
=> feat: add active liquid stacking route

apps/mobile/src/components/action-bar/action-bar-container.tsx, apps/mobile/src/components/page/page.layout.tsx
@edgarkhanzadian Looks like Action Bar got knipped by accident. This brings it back along with some cosmetic tweaks to match the designs.
=> fix(mobile): bring back action bar, tweak the design

apps/web/app/components/stacks-account-loader.tsx, apps/web/app/features/stacking/direct-stacking-info/get-has-pending-direct-stacking.ts, apps/web/app/features/stacking/direct-stacking-info/get-has-pending-stack-extend.ts, apps/web/app/features/stacking/direct-stacking-info/get-has-pending-stack-increase.ts, apps/web/app/features/stacking/direct-stacking-info/use-get-has-pending-tx-query.ts, apps/web/app/features/stacking/direct-stacking-info/utils-pending-txs.ts, apps/web/app/features/stacking/hooks/stacking.query.ts, apps/web/app/features/stacking/liquid-stacking-active-info.tsx, apps/web/app/features/stacking/pooled-stacking-info/get-delegation-status.ts, apps/web/app/features/stacking/pooled-stacking-info/use-delegation-status-query.ts, apps/web/app/features/stacking/pooled-stacking-info/use-get-pool-address-query.ts, apps/web/app/features/stacking/pooled-stacking-info/use-pooled-stacking-info.ts, apps/web/app/features/stacking/pooled-stacking-info/use-stacking-initiated-by.ts, apps/web/app/features/stacking/providers/fetch-fn.ts, apps/web/app/features/stacking/providers/stacking-client-provider.tsx, apps/web/app/features/stacking/start-pooled-stacking/components/preset-pools.tsx, apps/web/app/features/stacking/user-positions.tsx, apps/web/app/pages/stacking/liquid-stacking-active.tsx, apps/web/app/pages/stacking/stacking.tsx, apps/web/app/pages/stacking/types.ts, apps/web/app/pages/stacking/utils.ts, apps/web/app/routes/stacking/index.tsx, apps/web/app/store/addresses.ts, apps/web/app/utils/transactions.ts, packages/query/src/query-prefixes.ts, packages/query/src/stacking/stacking.query.ts
This pr adds stacked in a pool user positions
Also adds a bunch of queries that we will need along the way during development
=> feat: add stacked in pool user positions data

apps/web/wrangler.jsonc
Wrangler config changes needed to host our app
=> ci(web): host leather

.github/workflows/code-checks.yml, .github/workflows/crowdin-action.yml, apps/mobile/package.json, apps/mobile/src/features/approver/components/approver-buttons.tsx, apps/mobile/src/features/receive/receive-sheets/select-account.tsx, apps/mobile/src/features/send/components/recipient/v1/recipient.v1.tsx, apps/mobile/src/features/send/screens/select-account.tsx
This PR fixes `lingui` and adds a check to the CI.
It has been silently failing when it had compile issues and this means it doesn't sync with CrowdIn and add newly created keys
=> fix(mobile): fix lingui crowdIn sync

apps/web/app/features/stacking/components/pending-stack-extend-alert.tsx, apps/web/app/features/stacking/direct-stacking-info/components/action-buttons-row.tsx, apps/web/app/features/stacking/direct-stacking-info/components/active-stacking-info.tsx, apps/web/app/features/stacking/direct-stacking-info/components/liquid-stacking-info-grid.layout.tsx, apps/web/app/features/stacking/direct-stacking-info/components/liquid-stacking-info-grid.tsx, apps/web/app/features/stacking/direct-stacking-info/components/no-stacking-info.tsx, apps/web/app/features/stacking/direct-stacking-info/components/pending-stacking-info.tsx, apps/web/app/features/stacking/direct-stacking-info/liquid-stacking-info.tsx, apps/web/app/features/stacking/liquid-stacking-active-info.tsx, apps/web/app/features/stacking/pooled-stacking-active-info.tsx, apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-info-grid.tsx, apps/web/app/features/stacking/start-liquid-stacking/utils/preset-protocols.tsx, apps/web/app/features/stacking/start-pooled-stacking/components/preset-pools.tsx, apps/web/app/utils/stacking-pox.ts, apps/web/package.json, pnpm-lock.yaml
This pr adds active liquid stacked logic
Video
https://github.com/user-attachments/assets/c1f5467a-7ae0-4f6f-b69a-237664b3654f
=> feat(web): add liquid stacking active logic

apps/web/app/features/stacking/pooled-stacking-active-info.tsx, apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-action-buttons.tsx, apps/web/app/features/stacking/pooled-stacking-info/use-revoke-delegate-stx.ts
This pr adds stop pooling 
video (seems there was some bug in the wallet)
https://github.com/user-attachments/assets/61a43ce7-f3df-4ba8-8cd5-eb487b852850
=> feat(web): add stop pooling

apps/web/app/features/stacking/start-liquid-stacking/start-liquid-stacking.tsx, apps/web/app/features/stacking/start-pooled-stacking/components/choose-pooling-amount.tsx, apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx, apps/web/app/features/stacking/start-pooled-stacking/utils/stacking-pool-form-schema.ts
This pr adds increase pooling amount validation
video
https://github.com/user-attachments/assets/aa2307f2-4bca-4d3f-bb81-30e35e9b4839
=> feat(web): add increase pooling amount validation

.github/workflows/deploy-web.yml, apps/web/app/app.tsx, apps/web/app/features/analytics/analytics.ts, apps/web/app/features/analytics/use-on-route-change.ts, apps/web/app/features/sbtc-enroll/use-enroll-transaction.ts, apps/web/app/features/stacking/increase-liquid-stacking/utils/utils-increase-liquid-stacking.ts, apps/web/app/features/stacking/pooled-stacking-info/use-revoke-delegate-stx.ts, apps/web/app/features/stacking/start-pooled-stacking/utils/utils-allow-contract-caller.ts, apps/web/app/features/stacking/start-pooled-stacking/utils/utils-disallow-contract-caller.ts, apps/web/app/pages/sbtc-rewards/components/sbtc-rewards-faq.tsx, apps/web/app/pages/sbtc-rewards/sbtc-rewards.tsx, apps/web/app/pages/stacking/components/stacking-faq.tsx, apps/web/app/store/addresses.ts, apps/web/app/utils/external-links.ts, apps/web/package.json, apps/web/workers/csp.ts, packages/rpc/src/methods/stacks/stx-transfer-stx.ts, pnpm-lock.yaml
Add Segment analytics, and tracking events
=> feat(web): add segment, events, closes ENG-67

apps/web/app/app.tsx, apps/web/app/constants/default-meta-tags.ts, apps/web/app/features/sbtc-enroll/sbtc-enroll-button.tsx, apps/web/app/features/sbtc-enroll/use-enroll-transaction.ts, apps/web/app/pages/sbtc-rewards/components/acquire-sbtc-grid.layout.tsx, apps/web/app/pages/sbtc-rewards/components/acquire-sbtc-grid.tsx, apps/web/app/pages/sbtc-rewards/sbtc-rewards.tsx, apps/web/app/root.tsx, apps/web/app/routes/error-not-found.page.tsx, apps/web/app/routes/sbtc.page.tsx, apps/web/app/routes/stacking/liquid-stacking-active.page.tsx, apps/web/app/routes/stacking/liquid-stacking-increase.page.tsx, apps/web/app/routes/stacking/liquid-stacking.page.tsx, apps/web/app/routes/stacking/pooled-stacking-active.page.tsx, apps/web/app/routes/stacking/pooled-stacking.page.tsx, apps/web/app/routes/stacking/stacking.page.tsx, apps/web/app/store/addresses.ts, apps/web/package.json, apps/web/tests/sbtc.spec.ts, pnpm-lock.yaml
Closing out Friday with some last QA issues, sBTC page looking better now
=> feat(web): enroll button, closes PRO-49

apps/mobile/android/app/src/main/AndroidManifest.xml, apps/mobile/android/build.gradle, apps/mobile/app.config.js, apps/mobile/ios/Podfile.lock, apps/mobile/ios/leatherwalletmobile/Info.plist, apps/mobile/package.json, apps/mobile/src/features/qr-scanner/qr-scanner-camera.tsx, apps/mobile/src/features/qr-scanner/qr-scanner-chrome.tsx, apps/mobile/src/features/qr-scanner/qr-scanner-frame.tsx, apps/mobile/src/features/qr-scanner/qr-scanner.tsx, apps/mobile/src/features/qr-scanner/use-camera-permission.ts, apps/mobile/src/features/send/components/recipient/recipient-guard-sheet.tsx, apps/mobile/src/features/send/components/recipient/recipient-input.tsx, apps/mobile/src/features/send/components/recipient/recipient-qr-scanner.tsx, apps/mobile/src/features/send/components/recipient/recipient-qr-sheet.tsx, apps/mobile/src/features/send/components/recipient/recipient-selector/recipient-selector.tsx, apps/mobile/src/features/send/components/recipient/recipient-sheet.tsx, apps/mobile/src/features/send/components/recipient/recipient-toggle.tsx, apps/mobile/src/features/send/components/recipient/recipient.tsx, apps/mobile/src/features/send/components/recipient/use-recipient-evaluator.ts, apps/mobile/src/features/send/components/recipient/use-recipient-state.ts, eslint.config.js, packages/bitcoin/package.json, packages/bitcoin/src/bip21/bip21.ts, packages/bitcoin/src/index.ts, pnpm-lock.yaml
Enables QR code scanning in the send flow. Closes PRO-7, LEA-1869
https://github.com/user-attachments/assets/b7aecdae-5fab-45c7-a7ad-1d9f3e128f4f
https://github.com/user-attachments/assets/c89657f0-e700-48f5-89c5-1fd78d6eb091
https://github.com/user-attachments/assets/3b154e6f-5529-4f79-b91b-d245094a55f1
=> Add QR scanning to Send

apps/web/app/pages/sbtc-rewards/components/get-sbtc-grid.layout.tsx, apps/web/app/pages/sbtc-rewards/components/get-sbtc-grid.tsx, apps/web/app/pages/sbtc-rewards/components/sbtc-rewards-faq.tsx, apps/web/app/pages/sbtc-rewards/sbtc-rewards.tsx, apps/web/app/pages/stacking/components/earn-instructions.tsx, apps/web/app/pages/stacking/components/liquid-stacking-explainer.tsx, apps/web/app/pages/stacking/components/stacking-explainer.tsx, apps/web/tests/sbtc.spec.ts
=> refactor(web): do not use acquire wording

apps/web/app/components/explainer.tsx, apps/web/app/pages/stacking/components/earn-provider-table.tsx, apps/web/app/pages/stacking/components/liquid-stacking-explainer.tsx, apps/web/app/pages/stacking/components/stacking-explainer.tsx
This pr removes unnecessary dummy icons on stacking page
=> feat(web): remove unnecessary icons

apps/web/app/components/protocol-overview.tsx, apps/web/app/features/stacking/components/stacking-conditions.tsx, apps/web/app/features/stacking/components/stacking-form-steps-panel.tsx, apps/web/app/features/stacking/components/stacking-layout.tsx, apps/web/app/features/stacking/increase-liquid-stacking/increase-liquid-stacking.tsx, apps/web/app/features/stacking/start-liquid-stacking/start-liquid-stacking.tsx, apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx, apps/web/app/pages/stacking/components/earn-provider-table.tsx
This pr 
- adds protocol overview in liquid stacking flow (with hardcoded data for now)
- fixes ui in pooled/liquid stacking flows
=> feat(web): add protocol overview component

apps/mobile/src/features/browser/browser/search-bar/search-input.tsx
Delete search text with X button
https://github.com/user-attachments/assets/0310b36d-1a86-4ace-b03d-c561106a1ed1
=> feat: clean search text with X button [LEA-2596]

apps/mobile/src/features/accounts/components/browser-loading.tsx, apps/mobile/src/features/browser/browser/browser-active-state.tsx
https://github.com/user-attachments/assets/72543d2d-9360-4134-8fd7-5ccdf798a36d
=> Loading state for page loading in the browser [LEA-2488]

apps/web/app/components/icons/sbtc-logo.tsx, apps/web/app/components/value-displayer/default-value-displayer.tsx, apps/web/app/components/value-displayer/reward-value-displayer.tsx, apps/web/app/data/data.ts, apps/web/app/features/stacking/components/stacking-info-grid.layout.tsx, apps/web/app/features/stacking/direct-stacking-info/components/liquid-stacking-info-grid.layout.tsx, apps/web/app/features/stacking/direct-stacking-info/components/liquid-stacking-info-grid.tsx, apps/web/app/features/stacking/direct-stacking-info/liquid-stacking-info.tsx, apps/web/app/features/stacking/pooled-stacking-active-info.tsx, apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-action-buttons.tsx, apps/web/app/features/stacking/pooled-stacking-info/pooled-stacking-info-grid.tsx
This pr
- adds fast pool v2 in staking pools list
- fixes stacking active pages responsiveness
=> feat(web): add fast pool v2

apps/mobile/src/components/action-bar/action-bar-container.tsx, apps/mobile/src/components/sheets/sheet.layout.tsx, apps/mobile/src/features/send/send-sheet.tsx, apps/mobile/src/features/send/send.tsx, apps/mobile/src/features/send/utils.ts, packages/ui/src/components/sheet/sheet.native.tsx
Send will now omit account selection, when opened from account screen.
https://github.com/user-attachments/assets/a6359c0d-f3fb-46b9-84dd-080c12d533dc
=> Pre-select the account when opening Send from account screen, closes LEA-2004

apps/mobile/src/features/send/components/error-state.tsx, apps/mobile/src/features/send/forms/btc/btc-loader.tsx, apps/mobile/src/features/send/forms/stx/stx-loader.tsx
Adds error view to the send form, with ability to reload.
https://github.com/user-attachments/assets/168dfcf0-3343-4be5-88fb-c924b79cfa67
=> feat(mobile): add send form error view, closes LEA-2362

apps/web/app/pages/stacking/components/stacking-provider-table.tsx
=> fix(web): hydration err

apps/web/app/features/stacking/start-liquid-stacking/utils/types-preset-protocols.ts, apps/web/app/features/stacking/start-liquid-stacking/utils/utils-liquid-stacking-stx.ts
This pr fixes liquid stacking contract addresses and args
=> fix(web): liquid stacking contract addresses and args

apps/mobile/src/app/account/[account]/balances.tsx, apps/mobile/src/app/balances/index.tsx, apps/mobile/src/app/home/home.tsx, apps/mobile/src/features/account/account.tsx, apps/mobile/src/features/activity/activity-list.tsx, apps/mobile/src/features/balances/balances.tsx, apps/mobile/src/features/balances/bitcoin/runes-balance.tsx, apps/mobile/src/features/balances/constants.ts, apps/mobile/src/features/balances/stacks/sip10-balance.tsx, apps/mobile/src/features/balances/utils/sort-sip10-balances.spec.ts, apps/mobile/src/features/balances/utils/sort-sip10-balances.ts
This PR adds some improvements to the `Tokens` list + pages:
- sort tokens 
- use `FlashList` when rendering to improve
**Demo**
https://github.com/user-attachments/assets/14e0c687-2744-4b7a-b9cf-39987e224776
=> fix(mobile): sort tokens, add FlashList for performance, ref LEA-2310

apps/web/.env.example, apps/web/app/app.tsx, apps/web/app/constants/environment.ts, apps/web/app/features/stacking/hooks/use-pool-info.tsx, apps/web/app/queries/market-data/btc-market-data.query.ts, apps/web/app/queries/market-data/market-data.query.ts, apps/web/app/queries/market-data/stx-market-data.query.ts, apps/web/app/services/init-app-services.ts, apps/web/app/services/web-http-cache.service.ts, apps/web/app/services/web-settings.service.ts, apps/web/app/store/fiat-currency.ts, apps/web/package.json, apps/web/workers/csp.ts, pnpm-lock.yaml
This pr adds leather service package and market data
=> feat(web): add leather service package

apps/web/app/features/stacking/hooks/use-active-pool-info.tsx, apps/web/app/features/stacking/hooks/use-pool-info.tsx, apps/web/app/features/stacking/start-liquid-stacking/utils/utils-preset-protocols.ts, apps/web/app/features/stacking/start-pooled-stacking/components/preset-pools.tsx, apps/web/app/features/stacking/start-pooled-stacking/start-pooled-stacking.tsx, apps/web/app/features/stacking/user-positions.tsx, apps/web/app/pages/stacking/components/stacking-provider-table.tsx, apps/web/app/queries/stacking-tracker/pools.ts, apps/web/app/queries/stacking-tracker/protocols.ts
This pr adds data in
- pooled stacking user position
- liquid stacking table
=> feat(web): add proper pooled stacking data in user positions

apps/web/app/components/external-link.tsx, apps/web/app/layouts/footer/footer.layout.tsx, apps/web/app/layouts/footer/footer.tsx, apps/web/app/utils/external-leather-navigator.ts
Copies footer design shared with framer
=> refactor(web): align footer, closes ENG-44

apps/web/app/layouts/footer/footer.tsx
=> fix(web): add external link icon

apps/web/app/layouts/footer/footer.tsx, apps/web/app/layouts/nav/nav-item.layout.tsx
I've changed footer / sidebar nav item in tandem in the web app and on framer to get them as close as possible
=> fix(web app): nav & footer tweaks
